### ISSUE TITLE
Make some default fixtures 

### ISSUE THREAD

**Issue by jinpark** [DjangoGirls/djangogirls#103]
When I was trying to contribute to the site, was kind of a pain to create a bunch of fake applications, so it would be nice if we could get some fake fixtures in there to pre populate some data in the database

**Comment by jinpark** [comment]
Forgot to mention, it would be nice if we could do a small `dumpdata` and anonymize  the emails and ids for a few small events :)

**Comment by olasitarska** [comment]
:+1:

**Comment by aniav** [comment]
Done! There is a sample_db.json file in the root directory now :)
