### ISSUE TITLE
Add first and last name to exported csv

### ISSUE THREAD

**Issue by jinpark** [DjangoGirls/djangogirls#111]
`hawkowl` in slack wanted names in the csv export. Very reasonable request, I can work on this after we get https://github.com/DjangoGirls/djangogirls/issues/101 in

**Comment by olasitarska** [comment]
I think this is actually part of issue #106, isn't it?

**Comment by jinpark** [comment]
Bleh, yup. I forgot that the names are included in the questions. Closing :P
