### ISSUE TITLE
Add FAQ page to main site. 

### ISSUE THREAD

**Issue by williln** [DjangoGirls/djangogirls#112]
This is newbie-friendly! 

1. Take the [Organier's FAQ](http://organize.djangogirls.org/faq/index.html), pull out the questions that aren't specific to organizing, and duplicate them on an /faq/ page for the main Django Girls site. 
2. Site should be linked from the bottom footer under "Django Girls." 
3. URL should be /pages/faq

**Comment by amureki** [comment]
@williln maybe we should create an app for FAQ? Or just leave it as flatpage?

**Comment by olasitarska** [comment]
@amureki I think it's better to have it as html in repository, because people can PR against it! :)

**Comment by andrayantelo** [comment]
I think this is closed by #147

**Comment by olasitarska** [comment]
Thanks!
