### ISSUE TITLE
Fix weird ordering in /applications/ page

### ISSUE THREAD

**Issue by jinpark** [DjangoGirls/djangogirls#117]
On the applications page, the ordering is wonky and I'm not really sure why

![image](https://cloud.githubusercontent.com/assets/1847812/9162321/4d49c57a-3f80-11e5-8460-33347f384d92.png)

**Comment by phalt** [comment]
Could this be something to do with how records are collected from the database? Perhaps there is no ordering?

**Comment by phalt** [comment]
@jinpark which page are you seeing this on? If we know where to start looking it'll help us discover a fix quicker! :grin:

**Comment by jinpark** [comment]
For the seoul group, `https://djangogirls.org/seoul/applications/` page

I thought there was only one `/applications` page!

**Comment by phalt** [comment]
@jinpark I've been investigate this, this evening and I can't seem to reproduce any weird state. Are you sure it is not just because you've set a filter at the top of the page?

**Comment by phalt** [comment]
@jinpark I have a fix into master, should be soon so feel free to close this when you're happy!

**Comment by helenst** [comment]
This is deployed now :) Looks good on Coventry!

**Comment by jinpark** [comment]
LGTM here as well! Closing the issue! Thanks!!! :+1:
