### ISSUE TITLE
Application number should correlate to the url

### ISSUE THREAD

**Issue by jinpark** [DjangoGirls/djangogirls#118]
For the seoul chapter at least
`https://djangogirls.org/seoul/applications/424` links to application number `110`

It would make more sense to have the url be `https://djangogirls.org/seoul/applications/110` since it would be easier to refer and link to

N.B. This might break a lot of existing urls out in the wild that are between teams so might need to do a site wide notification about this change when it gets deployed

**Comment by RachellCalhoun** [comment]
Our team had some confusion over this. I hope the url and app number can be the same to eliminate unnecessary miscommunication.

**Comment by hassanabidpk** [comment]
+ Also when you click on "Save and go to next" it takes you some random application. After 110, I would ideally want to be at 111.

**Comment by helenst** [comment]
@jinpark this seems like a nice idea, url breakage will need to be handled but I think this would be good to have.

@hassanabidpk This should probably be a separate issue, but it seems like the "save and go to next" is intentionally random. Maybe it should be re-labelled to say it's random, and perhaps a separate button which takes you to the next in sequence, what do you think?

**Comment by jinpark** [comment]
How about

Save & Go Previous | Save | Save & Go Next | Save & Go Random
------------ | ------------- | ------------ | -------------

**Comment by olasitarska** [comment]
I think that's two options too many ;)

**Comment by hassanabidpk** [comment]
Agree with @helenst  . Having two options is reasonable.

**Comment by williln** [comment]
Also, it's in our blog post about how we score that apps are scored randomly, so no one is scored worse just because they are at the bottom of the pile. I don't think we should change that.

**Comment by jinpark** [comment]
I'm ok with either way, I just want the application numbers/url sorted out :D

**Comment by aniav** [comment]
So all in all this issue is about changing how the url is created. We should not change the behaviour of save & go to next. Summarising it up so we have a clear view (and because we have sprints on Django Under The Hood and I want this to be clear for anyone).

**Comment by jinpark** [comment]
thanks @aniav ! I can have a PR for this fairly soon I think

**Comment by aniav** [comment]
Awesome! Keeping my fingers crossed! :)

**Comment by jinpark** [comment]
PR up for this one. Let me know if you have any problems :)

**Comment by aniav** [comment]
Closing as it is now done!
