### ISSUE TITLE
Fix the date of the event in Sao Jose dos Campos

### ISSUE THREAD

**Issue by taniaa** [DjangoGirls/djangogirls#129]
Will take place in November not October: https://djangogirls.org/events/

![captura de tela 2015-08-24 as 09 59 56](https://cloud.githubusercontent.com/assets/1102067/9440735/b9b1cb28-4a47-11e5-837d-a1081e09165f.png)
![captura de tela 2015-08-24 as 10 00 06](https://cloud.githubusercontent.com/assets/1102067/9440736/b9b66214-4a47-11e5-9596-94d16691d7db.png)

**Comment by williln** [comment]
Hi @taniaa! I've updated this event. For future reference, I think you can change this yourself at https://djangogirls.org/admin/core/event/ :tulip: :rose:

**Comment by taniaa** [comment]
Hi @williln! Of course but I don't have access... Let me know how can I do this.

**Comment by williln** [comment]
I think the organizers have access to that page? I could be wrong, though. Are you an organizer for that event @taniaa? If not, that explains why you don't have access. :-) If you should be an organizer for that event, then have one of the existing organizers email us to have you added!

**Comment by taniaa** [comment]
I'm not a organizer of Django Girls or Django programmer. I'm from Python community in general and Pyladies Brazil. If I can help in something else just tell me. :)

**Comment by williln** [comment]
I see! Thanks for noticing the discrepancy :-) Sometimes when we set up events, the organizers don't know when their event will be held exactly, and then they set their date but don't realize they need to change it for the homepage, too. 

There's a list of issues for the website if you feel like jumping in! https://github.com/DjangoGirls/djangogirls/issues Just comment on the issue if you have any questions! Thank you! :balloon: :lollipop:

**Comment by taniaa** [comment]
Ok! I will spreed it to my Django programmers friend ;)

Good look with organization! See you in the event!
