### ISSUE TITLE
catch-all url for event

### ISSUE THREAD

**Issue by rebkwok** [DjangoGirls/djangogirls#13]
Hi

In core/urls.py, there is this line:
url(r'^(?P<city>[\w\d/]+)$', 'core.views.event', name='event'),

This basically says "match djangogirls.org/ plus any combination of letters and go to the event view".  Then in core/views.py, there is a try/except clause on line 50 that says if the event page doesn't exist, redirect to /events.  When developing the jobs site, we've found that the url for /jobs/ redirects to /events when the trailing slash is omitted - the event url plus the redirect is a catchall url, so we can never get a 404 (any nonsense url e.g. djangogirls.org/sdfshdjkfkasejaoefjasdlk redirects to djangogirls.org/events).  

I can see that a workaround redirect has already been done for /admin in djangogirls/urls.py, but if the site is being expanded with more apps/sections, this will mean that it will need to be done for every url.  Is this how you'd prefer it to be done, or would it be better to add a prefix for event (/event/berlin etc - which admittedly will need to deal with the event pages already set up)

Thanks
Becky

**Comment by olasitarska** [comment]
Hi @rebkwok!

Yeah, I am aware of this for a while. I'd rather fix this (so all urls have / at the end, for example), than to change the url of every event we have. Especially if we're printing posters & stuff, djangogirls.org/london is better and easier to remember than djangogirls.org/event/london.

djangogirls.org/london/ is not as bad as djangogirls.org/event/london. We should redirect everything that doesn't have the last / to the same address with /. 

If the event does not exist, we could show 404 (but maybe with a big link to the events page?)

Do you want to work on this?

Thanks,
Ola

**Comment by rebkwok** [comment]
Sure, I would be happy to work on this :)

**Comment by rebkwok** [comment]
@olasitarska I'm mostly done with this - just wanted to check how you want to deal with events that exist, but are not live yet.  They can either throw a 404 like any other unmatched url, or they could redirect to a page saying something like "The event page for <city> will be coming soon!" (possibly only for cities with a future date, so the is_live flag can be used to deactivate past events if necessary.

**Comment by olasitarska** [comment]
I think the latter would be perfect! :) We could also say: if you want to contact organizers of this event, email them on [city]@djangogirls.org. It's always the city slug and @djangogirls.org.
