### ISSUE TITLE
Sponsor rows should not have margin top/padding bottom on smaller screen sizes

### ISSUE THREAD

**Issue by ryangallen** [DjangoGirls/djangogirls#150]
When viewing the sponsor logos on mobile screen sizes, the row margin/padding creates an odd looking space.

<img width="458" alt="screen shot 2015-10-26 at 10 28 06 pm" src="https://cloud.githubusercontent.com/assets/1379681/10747897/e280bfb2-7c30-11e5-82c7-dde6ef57c6c2.png">

**Comment by aniav** [comment]
I am looking at this :)

**Comment by aniav** [comment]
Fixed that! :)
