### ISSUE TITLE
Add "Add another job" button to submission page

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/djangogirls#159]
_From @williln on July 15, 2015 19:34_

On the success page, I think it'd be nice to have an "Add another job" button. A company may have several opportunities. 

_Copied from original issue: djangogirlsjobs/djangogirls#52_

**Comment by ulgens** [comment]
@aniav Is the task completed?

**Comment by aniav** [comment]
@ulgens seems so! Thank you, I am closing it :)
