### ISSUE TITLE
Add job/meetup forms could be formatted better

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/djangogirls#160]
_From @MarysiaLowas on July 24, 2015 19:1_

For now, all input fields in Add job/meetup forms are set to 260px but it would be nicer to have them wider. And we could also improve the forms layout but we would need to dive into crispy forms.

_Copied from original issue: djangogirlsjobs/djangogirls#68_

**Comment by MarysiaLowas** [comment]
Remove 'crispy_forms' as they are deprecated. Find another library or try to use pure bootstrap.

**Comment by MarysiaLowas** [comment]
I am working on this one :dango:

**Comment by ulgens** [comment]
@aniav Is that issue resolved?

**Comment by aniav** [comment]
@ulgens yes! Thanks for reminding! :)
