### ISSUE TITLE
populate_database script is out-of-date

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/djangogirls#161]
_From @MarysiaLowas on July 24, 2015 17:23_

Most probably populate_database script is out of date. I haven't run it but it's ages till we last updated it.

_Copied from original issue: djangogirlsjobs/djangogirls#66_

**Comment by MarysiaLowas** [comment]
This script should be removed. It's not working any more and it's no needed at the moment.

**Comment by MarysiaLowas** [comment]
Actually, the populate_database script is still working. However, it generates jobs and meetups with are already published but don't have any reviewer assigned to it. In a normal (manual) flow, such a situation is not possible. New jobs and meetups don't have any reviewer but the reviewer is assigned automatically during the "Assign" or "Restore" action. So the script behaviour can be misleading.
