### ISSUE TITLE
Show more geography data in meetups

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/djangogirls#162]
_From @williln on July 15, 2015 20:11_

In /community/meetups, we're only displaying the city. As this page grows, we may want to display city and country, and possibly city/state-or-province/country. There are two Portlands in the US, for example. 

With that in mind, we may want to collect state or province data for meetups, so we at least have it. It would also help with a Phase 2 "filtering" option, where people could filter by country, and then state/province, etc. 

We are also not displaying timezone. PyLadies has a whole remote chapter now, so timezone is something we might want to collect, also, for remote-friendly meetups. 

_Copied from original issue: djangogirlsjobs/djangogirls#61_

**Comment by aniav** [comment]
_From @MarysiaLowas on July 23, 2015 11:43_

FYI, I'm looking into this one.

**Comment by aniav** [comment]
_From @rebkwok on July 23, 2015 11:56_

@MarysiaLowas the timezone should be relatively easy to implement. Let me know if you need any help - I (painfully) implemented timezone support over a huge django app at work, so there may be some immediate tips I can give you if something isn't obvious

**Comment by MarysiaLowas** [comment]
This issue has been split into: #165, #166, #167

**Comment by aniav** [comment]
Closing :)
