### ISSUE TITLE
Add # upcoming meetups to the footer counters?

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/djangogirls#163]
_From @rebkwok on July 4, 2015 4:37_

As mentioned in comment here:
https://github.com/djangogirlsjobs/djangogirls/blob/master/templates/global/footer.html#L45

_Copied from original issue: djangogirlsjobs/djangogirls#36_

**Comment by cgl** [comment]
@aniav I think this issue is already merged within @sodevious 's commit. You can close it.
