### ISSUE TITLE
Add timezone support for meetups

### ISSUE THREAD

**Issue by MarysiaLowas** [DjangoGirls/djangogirls#166]
Extracted from #162 

> We are also not displaying timezone. PyLadies has a whole remote chapter now, so timezone is something we might want to collect, also, for remote-friendly meetups. 

Discussed with @aniav 
We shall add a mandatory timezone dropdown next to the _Meetup start date_ field.
Add timezone info when displaying the meetup info (_Community_, _Meetups_, _Meetup details_ pages)

This might be useful:
[django 1.4 how to automatically get user's timezone from client](http://stackoverflow.com/questions/10235956/django-1-4-how-to-automatically-get-users-timezone-from-client)

**Comment by olasitarska** [comment]
To be honest, I think this doesn't make sense to spend time on until we grow this page enough for this to actually become an issue. Closing for now, but let's reopen when we see this being a problem :)
