### ISSUE TITLE
Add sponsor functionality doesn't work

### ISSUE THREAD

**Issue by lyapun** [DjangoGirls/djangogirls#175]
Hello!

1. G to add sponsor page in admin interface - https://djangogirls.org/admin/core/sponsor/add/
2. Fill all fields and click "save"
3. Then you will be redirected to sponsors list and you can see message about "new sponsor was added", but you will not see this sponsor in sponsors list, and else will not see this sponsor in event page.

I think that something broken with assigning sponsor to particular event.

Would be nice to have this fixed ASAP, because I have 2 sponsors who is waiting to be added to site.

Thanks

**Comment by aniav** [comment]
Hey @lyapun I have looked into this. Basically to attach a sponsor to a specific page you need to go to that page content called "partners" or "sponsors" or something like that (depending on website) and attach sponsors through an inline form there. Adding sponsors through the view you provided will simply add them to the main list and won't attach them anywhere.

I have removed Sponsors and Coaches from the main menu to avoid confusion :)

**Comment by lyapun** [comment]
@aniav But it used to work on separate page. Also, on separate page I was be able to change order of sponsors, so I think it's regression.

**Comment by lyapun** [comment]
Also, it's so hard to find sponsor in dropdown, because they are not sorted in alphabetical order

**Comment by aniav** [comment]
I will try t

**Comment by aniav** [comment]
That's because we have merged a PR for #27 recently. I understand your problem but I am unable to fix that any time soon. Keeping this issue reopened so maybe someone else will be able to work on that.

**Comment by parodia** [comment]
My PR https://github.com/DjangoGirls/djangogirls/pull/245 changed sponsors order to alphabetic one :)
