### ISSUE TITLE
Displaying list of applications for organizers with sorting

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#18]
> This issue is a part of [Project: application process](https://github.com/DjangoGirls/djangogirls/wiki/Project:-Application-process) & the work is happening on [applications branch](https://github.com/DjangoGirls/djangogirls/tree/applications)

The goal of this is to have a list of all `Application` objects for given `Form` listed somewhere. Applications should be listed anonymously, with just an ID and date of creation. 
Url: http://djangogirls.org/city/applications/
Access should be restricted to organizers of this event only. 

This is a first part of the scoring / triaging system.

**Comment by phalt** [comment]
Gonna give this a go today. I'm not a css whiz, so I'll just start some work on providing lists of applications for events, filtered on events and only viewable by organisers of that event.

**Comment by andyosuna** [comment]
If this is okay I can take over and help with the styling!

**Comment by phalt** [comment]
@andyosuna Sure, I think @olasitarska merged the progress I did into the `applications` branch

**Comment by olasitarska** [comment]
Yes @andyosuna, go ahead! :)

**Comment by andyosuna** [comment]
I believe the applications shouldn't link to a detail page, like they do now. Only styled the applications list for now :smile_cat:

**Comment by phalt** [comment]
@andyosuna The link goes to the detail view described [in this issue](https://github.com/DjangoGirls/djangogirls/issues/19). We can change it to a button instead, however.

**Comment by phalt** [comment]
@olasitarska What type of sorting do we want for this view? Sorting based on the state of the applications? newest/oldest/accepted/rejected?

**Comment by olasitarska** [comment]
I think we only need sorting by score for now -- I added it now :)
