### ISSUE TITLE
Please clarify that local posts will not be migrated to pythonanywhere   

### ISSUE THREAD

**Issue by P3nny** [DjangoGirls/djangogirls#180]
During django girls cologne some girls were irritaded/frustrated that post froms the local app are not migrated to pythonanywhere. 

Chapter 12:" Creating the database on PythonAnywhere"
>"Here's another thing that's different between your own computer and the server: it uses a different >database. So the user accounts and posts can be different on the server and on your computer." 

Perhaps it would be good to point out that the local posts will definetly be lost on the server because on pythonanywhere we are using a different database.

**Comment by olasitarska** [comment]
This is a repository for the Django Girls website, not the tutorial. @P3nny, would you mind re-adding it [here](https://github.com/DjangoGirls/tutorial)? Sorry for the confusion, and thanks for reporting! :)
