### ISSUE TITLE
Create a Contact form

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#185]
In order to decrease the amounts of email overall, and avoid many "I really wanna get in touch with Warsaw event, but I'm writing to hello@djangogirls.org" cases, maybe we could build a simple Contact from that would send an email to chosen chapter, letting people choose either Django Girls HQ or local events?

Inspiration: http://creativemornings.com/contact

Ideally that would also have a small FAQ above the contact form to answer the most common questions. I think @patjouk can provide that list of questions by now :)

**Comment by mmoravcik** [comment]
Mine!

**Comment by patjouk** [comment]
If you want to add some FAQ, I made a small list in the [organizer manual](https://github.com/DjangoGirls/organizer-manual/tree/master/faq). You can also add an entry for people that what to register when an event is not opened yet. If you're not sure what to write, I'll add it myself :wink:

**Comment by mmoravcik** [comment]
There already is /faq page.. https://djangogirls.org/faq/

Maybe we can just update that and add link from Contact page?

**Comment by patjouk** [comment]
It's a good idea!
I'll open an issue ;)

**Comment by mmoravcik** [comment]
https://github.com/DjangoGirls/djangogirls/pull/188
