### ISSUE TITLE
Displaying detail of application and scoring for organizers

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#19]
> This issue is a part of [Project: application process](https://github.com/DjangoGirls/djangogirls/wiki/Project:-Application-process) & the work is happening on [applications branch](https://github.com/DjangoGirls/djangogirls/tree/applications)

Once we have a list of all applications for organizers (#18), then we need to create an application detail view. This also needs to be restricted to organizers of the city only. 

On this page, you should see:
- all the questions & answers for the application
- at the end, possibility to score application in the scale of 1-5 and skip scoring for this application. Organizers should also have a way to add a comment to their score.

Buttons:
- save
- save and go to next application

Scores of other organizers should not be visible until you score the application yourself.

This also requires adding a model with scores.

**Comment by phalt** [comment]
I'm going to (hopefully) complete this view today, along with the ability to score the application. It won't look pretty but the backend functionality shouldn't take me more than a few hours.

**Comment by asendecka** [comment]
I keep my fingers crossed! :+1:
