### ISSUE TITLE
Update readme to include instructions on how to create PostgreSQL database

### ISSUE THREAD

**Issue by peconia** [DjangoGirls/djangogirls#192]
The settings have been changed to use PostgreSQL instead of SQLite. It would be helpful to add instructions on how to install and create a database locally as using PostgreSQL is not as straightforward as SQLite.

**Comment by ulgens** [comment]
Is anybody working on it? If not, i want to dive in.

**Comment by peconia** [comment]
@ulgens I am not working on it so feel free :)
