### ISSUE TITLE
The Sort by score function on the attendees application doesn't work

### ISSUE THREAD

**Issue by shante66** [DjangoGirls/djangogirls#199]
![pasted image at 2016_01_12 01_55 am](https://cloud.githubusercontent.com/assets/13355964/12263677/18e102da-b929-11e5-99d0-b264e0ffd1ce.png)

**Comment by aniav** [comment]
This has already been fixed but probably not deployed. @patjouk could you deploy the current master? Thank you! :)

**Comment by aniav** [comment]
Also @shante66 could you blur out the emails in the screen and reupload it? Currently someone can see what are the scores of some people :)

**Comment by shante66** [comment]
Done sorry about that :)

**Comment by patjouk** [comment]
Website redeployed: it's fixed :wink: 
Thanks @aniav :cake:
