### ISSUE TITLE
Assigning people to groups: accepted / waitlisted / rejected

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#20]
> This issue is a part of [Project: application process](https://github.com/DjangoGirls/djangogirls/wiki/Project:-Application-process) & the work is happening on [applications branch](https://github.com/DjangoGirls/djangogirls/tree/applications)

On the application listing (#18), organizers should have a way to add people to following groups:
- accepted
- waitlisted
- rejected

Either by assigning one person to a group, or bulk assigning (like in Django admin with actions). 

It'd be also good to provide a way to filter people by group.

**Comment by andyosuna** [comment]
This is partially done, only missing the "waitlist" group
