### ISSUE TITLE
Get a Sticker for a correct environment

### ISSUE THREAD

**Issue by ceaess** [DjangoGirls/djangogirls#209]
Hi! I think it could work very well to implement a RailsBridge style "get a sticker when your computer is set up correctly" event workflow. [Here](http://docs.railsbridge.org/installfest/get_a_sticker) is an example of the pattern RailsBridge uses. I've seen this do much to eliminate environment problems during RailsBridge events, and I think it could work well for helping do the same in DjangoGirls. Would a pull request be accepted if I added a section like this to our "Installation" sections?

**Comment by olasitarska** [comment]
We try to keep the tutorial appropriate for online use too, so I'm afraid we can't do that.

**Comment by sigmavirus24** [comment]
Could the section not have a header at the top that if you're using the tutorial online then you should run through the steps yourself to ensure your environment is set up correctly? Having something like a checklist to help you make sure the installation happened appropriately seems beneficial.
