### ISSUE TITLE
Sending emails to chosen groups

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#21]
> This issue is a part of [Project: application process](https://github.com/DjangoGirls/djangogirls/wiki/Project:-Application-process) & the work is happening on [applications branch](https://github.com/DjangoGirls/djangogirls/tree/applications)

Organizers should have a way to send mass email to choosen groups of people (accepted, waitlisted, rejected), as well as just individuals who applied for the workshop. All emails should go from [city]@djangogirls.org. We will use SendGrid (or other option) to send those emails. 

We should also provide organizers with the history of sent emails through our system.

**Comment by lightstrike** [comment]
Is creating HTML templates for these emails considered part of this issue or should that be created separately?

**Comment by olasitarska** [comment]
Yeah, it's considered as a part. If you would rather submit two pull requests, go ahead :)

**Comment by olasitarska** [comment]
Let's do it on just plain text emails for now, as HTML pretty emails are stopping us from shipping this :rocket:!

**Comment by lightstrike** [comment]
Solid plan!
