### ISSUE TITLE
Add captchas

### ISSUE THREAD

**Issue by andyosuna** [DjangoGirls/djangogirls#210]
https://www.google.com/recaptcha/intro/index.html

Prevent trolls' bots from doing 500+ applications in a sitting :smile:

**Comment by patjouk** [comment]
I'm on it.

**Comment by patjouk** [comment]
Fixed it with #211. The captcha are quite ugly so I'll change it with recaptcha as soon as possible. Sorry again about that! I'll clean your database :wink:
