### ISSUE TITLE
Impossible to translate newletter question in application form

### ISSUE THREAD

**Issue by patjouk** [DjangoGirls/djangogirls#225]
The way the newsletter question [is created](https://github.com/DjangoGirls/djangogirls/blob/master/applications/utils.py) in the application form make it impossible for organizers to translate it.
Some websites are not in English so it would be awesome if they could change it :wink:

**Comment by olasitarska** [comment]
I currently don't have idea how to make this question unremovable, and still able to edit... I'll think about it :)

**Comment by olasitarska** [comment]
Also, idea -- should be sign up those people who want to receive newsletter from us to Campaign Monitor automatically?
