### ISSUE TITLE
Displaying RSVP status on attendees list

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#23]
> This issue is a part of [Project: application process](https://github.com/DjangoGirls/djangogirls/wiki/Project:-Application-process) & the work is happening on [applications branch](https://github.com/DjangoGirls/djangogirls/tree/applications)

On the application list created in #18, organizers should be able to see and filter people by RSVP status.

**Comment by robcharlwood** [comment]
Looking at this now...

**Comment by robcharlwood** [comment]
Hi @olasitarska :)

So I'm a little confused as to what is required here. Currently we dont have a RSVP status field on any model as far as I can see. If we add one, what should be the process for RSVPing? 

Email applicant with link to view where they can accept/reject/maybe? Or some other process?

Also I presume we are going to allow the applicant to update their responses? for example they say 'maybe' but decide then that they can go and wish to reject?

Some further clarification here would be very helpful!

Thank youuuu! :)

**Comment by robcharlwood** [comment]
To summarise. This ticket relies on others in this issue list. 

We need to send emails to accepted users with 'yes'/'no' links for them to click, create a model/fields to store attendee responses and allow organisers to filter these via ``/city/applications/``.
