### ISSUE TITLE
Additional question about opt-in to newsletter in each form

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#24]
> This issue is a part of [Project: application process](https://github.com/DjangoGirls/djangogirls/wiki/Project:-Application-process) & the work is happening on [applications branch](https://github.com/DjangoGirls/djangogirls/tree/applications)

Each form should have additional question (in English), at the end, asking if they want to receive newsletter from Django Girls about out future events and endeavours. This opt-in information should be saved on `Application` model. 

Which also reminds me, that it'd be good to let organizers mark question as `is_email` and validate these emails here.

**Comment by andyosuna** [comment]
I can try this one :)

**Comment by andyosuna** [comment]
This should have been done with merge #29 :)
