### ISSUE TITLE
After submitting a meetup you have an option to add another job but no meetup

### ISSUE THREAD

**Issue by MarysiaLowas** [DjangoGirls/djangogirls#252]
After submitting a meetup, you're redirected to the confirmation page which let you add another Job Opportunity but not another Meetup announcement.

That's because both create_job and create_meetup views redirect to the same view - confirm_submission - but it deals only with Job Opportunities.

![add_another_meetup](https://cloud.githubusercontent.com/assets/8274152/14225812/afa8b3ca-f8d0-11e5-8b44-cb791bb5be29.png)

**Comment by jitendraag** [comment]
I think we should consider making two confirmation pages: One for meetup submission and another for job / opportunity submission.

**Comment by phalt** [comment]
@MarysiaLowas Just merged a fix by @jitendraag so can I close this? 😄

**Comment by MarysiaLowas** [comment]
@phalt yeah, sure :) Thanks!
