### ISSUE TITLE
Automatically openning and closing application form based on date

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#26]
There is a `open_from` and `open_until` field on the `Form` model. We should respect that when displaying the form page.

**Comment by eddiebragg** [comment]
Hi,

Should this not show the page and not accept application submissions when not within the date range?

**Comment by olasitarska** [comment]
@eddiebragg Yeah, exactly, no one except organizers should be able to access /<city>/apply/ view if form is not within the date range.

**Comment by eddiebragg** [comment]
@olasitarska I take it if the two dates are not filled in the application is always open? The can have null values.

**Comment by olasitarska** [comment]
Yes!
