### ISSUE TITLE
Empty applications list should still show filters

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/djangogirls#262]
When I filter the applications list to show subset of applications (e.g. all RSVP rejected) if there are no applications with that status, it just says "Nothing to see here" and does not show the filtering options. It would be good to still show those so you can continue clicking through to other lists.

**Comment by jitendraa** [comment]
![new-filters](https://cloud.githubusercontent.com/assets/58476/14760290/9eb4851a-095d-11e6-9931-4afec11697ae.png)

Trying to push this fix (as soon as I figure out how to push my fixes)
