### ISSUE TITLE
Alphabetize sponsors in admin 

### ISSUE THREAD

**Issue by williln** [DjangoGirls/djangogirls#265]
It's really hard to find the sponsor you need to add. I also think alphabetizing would cut down on adding duplicate sponsors, since we'd be able to find what we needed. I think this is probably pretty newbie-friendly? 

In two places: 

https://djangogirls.org/admin/core/sponsor/ 
<img width="1204" alt="screen shot 2016-04-20 at 9 37 46 am" src="https://cloud.githubusercontent.com/assets/2286304/14682691/97632c28-06db-11e6-9241-00a744a1d9b9.png">
 
https://djangogirls.org/admin/core/eventpagecontent/[event_number]/change/?_changelist_filters=page__event__exact%3D159%26q%3D
<img width="701" alt="screen shot 2016-04-20 at 9 20 54 am" src="https://cloud.githubusercontent.com/assets/2286304/14682917/e0451a68-06dc-11e6-8516-71f61eda0401.png">

**Comment by jitendraa** [comment]
@williln : Sponsor model users a 'position' field.
```

    position = models.PositiveIntegerField(null=False, blank=False,
                                           help_text="Position of the sponsor")
```

Any sorting is controlled by position field. (which is defined as sortable in admin).

**Comment by phalt** [comment]
@jitendraa You can use Django QuerySet `order_by` method to do this I believe https://docs.djangoproject.com/en/1.9/ref/models/querysets/#django.db.models.query.QuerySet.order_by

**Comment by jitendraag** [comment]
@phalt No, we can't. Unless we get rid of 'sortable' from Django Suit.

The system is designed to have a position element that defines sorting.

**Comment by aniav** [comment]
Sorting for sponsors is not usable any more as Sponsors are global and there should be one sponsor that is attached to many events not one sponsor of the same name per event. I have added sorting by name and searching by name.

**Comment by williln** [comment]
Thanks @aniav!
