### ISSUE TITLE
ManyToMany relationship for coaches and sponsors

### ISSUE THREAD

**Issue by elena** [DjangoGirls/djangogirls#27]

**Comment by olasitarska** [comment]
The goal here would be to remove ForeignKey fields from Sponsor and Coach models, to make them available for every event organizers and create ManyToMany fields 'coaches' and 'sponsors' on EventPageContent model. This way organizers don't have to duplicate data for coaches who coached on more than one event or sponsors who sponsored more than one event.

**Comment by aniav** [comment]
This was merged.
