### ISSUE TITLE
Reconsider use of nose-progressive

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/djangogirls#272]
It doesn't support Python 3 well (https://github.com/erikrose/nose-progressive/issues/73) so it is hard to set breakpoints and debug a test

I don't know if there's a good alternative (or perhaps it's worth moving to pytest ;)

**Comment by aniav** [comment]
I have removed nose-progressive and introduced py.test. I have also created an account for us on codedov for code coverage visualisation: https://codecov.io/gh/DjangoGirls/djangogirls 🎉

**Comment by helenst** [comment]
@aniav This is so awesome, thank you! :sparkling_heart:
