### ISSUE TITLE
Missing emoji on homepage

### ISSUE THREAD

**Issue by helenst** [DjangoGirls/djangogirls#283]
![support-us](https://cloud.githubusercontent.com/assets/217966/15601939/41f4704a-23ea-11e6-90a1-85dd668caae4.png)

I am on Ubuntu so probably don't have the right font.

perhaps https://pypi.python.org/pypi/django-emoji can help... it seems like a thing that django girls website should have installed ;-)

**Comment by aniav** [comment]
Hey @helenst I believe it is a Ubuntu specific thing. I have checked the emoji we are using there with http://emojipedia.org/two-hearts/  and it seems to be working basically everywhere since 2010. Can you check if this website gives you any reasonable emoji?

**Comment by helenst** [comment]
Ah, no it didn't work on that page either. But I found what I needed and installed `ttf-ancient-fonts` so now I see two little black hearts (I don't know what I have to do to get coloured hearts, my phone shows it in colour :) It sounds like it works by default for most people though, so maybe it's fine.

**Comment by helenst** [comment]
For the record ... colour emojis for Firefox: http://www.omgubuntu.co.uk/2016/03/enable-color-emoji-linux-svg-font sadly not Chrome. Now tempted to switch browsers for the full emoji experience :dolphin::sparkling_heart::tulip:

**Comment by aniav** [comment]
I think I can close this now ⚡
