### ISSUE TITLE
save & go to next from applications does not go to the next applicant

### ISSUE THREAD

**Issue by xrmx** [DjangoGirls/djangogirls#286]
If i am here:
https://djangogirls.org/turin/applications/4

i expect "save and go to next" to get me to the url with the next submission by id:
https://djangogirls.org/turin/applications/5

Instead i get to a different applicants everytime i click.

While this looks like is made on purpose i think the label of the button is misleading.

We voted collegially on another medium and have to copy the votes back so a button that brings me to the next applicant by id would be helpful.

UPDATE: why we don't voted directly on the platform is a good question :)

**Comment by aniav** [comment]
@xrmx the idea od Save and go to next is that it's always randomly picked so you don't vote on the same  people at the same time and you make your votes more reliable. I have changes the text on the button so the person knows the next application will be picked randomly. Thank you for your input :)

**Comment by xrmx** [comment]
Again, thanks!
