### ISSUE TITLE
Warning for admins displayed to applicants on rsvp

### ISSUE THREAD

**Issue by xrmx** [DjangoGirls/djangogirls#288]
When the applicants clicks the rsvp yes link the page show this warning:
```
Hi there! If you can see this message, it means people can't register to your event. If you want to open registrations, go to your form in the admin interface and make sure "Application process" fields are correctly configured.
```
It looks like this should be shown to logged admins only.

You can reproduce it here:
https://djangogirls.org/turin/rsvp/SwQ50mpDZnMqgD9Xrv7Esd0B

**Comment by aniav** [comment]
Fixed, thank you! :)

**Comment by xrmx** [comment]
Thanks!
