### ISSUE TITLE
Broken link using search function for tutorial

### ISSUE THREAD

**Issue by jdelbello** [DjangoGirls/djangogirls#294]
When searching in the Django tutorial, if the current page is among the search results, the link to the current page is broken.

For example,
1. Navigating to "Your first Django project!"
2. Searching for "runserver"
3. Clicking on the current page's link

It seems that the search results should be cleared and the view reset to the background page once a link within the search results is clicked.

**Comment by aniav** [comment]
Hi @jdelbello, thank you for creating this issue but I will have to close it - the search functionality is prepared fully by @gitbookio and we aren't able to fix it. Sorry and thank you for the time you have taken to fill the issue! Hugs! ✨
