### ISSUE TITLE
Testing for Applications app

### ISSUE THREAD

**Issue by phalt** [DjangoGirls/djangogirls#31]
As the Applications app grows and third parties start to contribute, we should probably add an automated testing suite so we can start preventing bugs :bug: and pep8 errors.

**Comment by aniav** [comment]
I would suggest CircleCi or TravisCi here :)

**Comment by olasitarska** [comment]
I added some tests today. Still missing tests for forms and views.

**Comment by olasitarska** [comment]
Done!
