### ISSUE TITLE
An item in /maceio is broken

### ISSUE THREAD

**Issue by aericson** [DjangoGirls/djangogirls#310]
Please see screenshot attached.

I believe the problem is in 
```html
    <div class="container without-background" id="Local">
        <div class="container without-background" id="local"> <!-- this line shouldn't be here -->
        <div class="row">
<div class="col-md-6">
<h3>Local</h3>
<p> O #2DjangoGirlsMaceió ocorrerá na Uninassau do Farol</p>
```

https://djangogirls.org/maceio/
![2016-10-27-202643_1850x744_scrot](https://cloud.githubusercontent.com/assets/692542/19789192/2e926b7a-9c84-11e6-8029-404fa6b13ace.png)

**Comment by patjouk** [comment]
Thanks for opening this issue. It's now fixed :wink:
