### ISSUE TITLE
Vagrant Environment

### ISSUE THREAD

**Issue by ulgens** [DjangoGirls/djangogirls#331]
Hey,

I think that creating a Vagrant environment for development purposes would be very useful. It could create an easier setup for starting and also more standardized dev. environment. Are there any specific reason not to do it?

**Comment by olasitarska** [comment]
Not sure if I've got an opinion on this -- I personally don't use vagrant, but maybe others do?

**Comment by helenst** [comment]
Recent Vagrant convert here! I think this sounds like a good idea. Things like postgresql setup can be tricky  on some platforms and this could make it easier for people to get set up and start contributing :smile:

**Comment by olasitarska** [comment]
Let's do it then! :)

**Comment by ulgens** [comment]
@olasitarska Can you assign the issue to me? :)

**Comment by normade** [comment]
Dear @ulgens, dear @olasitarska, good idea! There is a Vagrant box for Django contributors available [here](https://github.com/django/django-box) and we are using [this one](https://github.com/transcode-de/django-vagrant-box) made by @keimlink for our daily purposes, you could check the repository to see if you could use some or all features as well for the Django Girls Vagrant box.

**Comment by ulgens** [comment]
@normade I'll check them, thank you!

**Comment by ulgens** [comment]
I don't think this issue is relevant anymore.
