### ISSUE TITLE
[Core cleanup] Move ContactEmal to a separate app.

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/djangogirls#362]
Core app has grown a lot in the past months. We shouls move things not related to Event to other apps. While moving it to another app we will have to create migrations that move models to other app while maintaining the data. Django migrations can do that. Ping me for information on how to do that.

This issue is for the ContactEmail model and views.

**Comment by yakupadakli** [comment]
https://github.com/DjangoGirls/djangogirls/pull/392

**Comment by aniav** [comment]
This was done! 👍
