### ISSUE TITLE
Optimize applications page.

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/djangogirls#382]
Currently the applications page will create a DB query for each row in the applications list, to check if the request.user has already scored the application. This happens because the `scored_by_user` templatetag is using a db query. We should remove the query from the templatetag completelly. We should retrieve applications with their scores and anonymize them in python code while processing the list before passing it to the actual template and this way producing less queries.

**Comment by vanessa** [comment]
Hey, @aniav! I'd like to know if this is still needed given the creation date. If yes, I'd like to give it a try, is that okay? 🙂

**Comment by aniav** [comment]
@vanessa as far as I know yes, this is still needed :) Let me know if you need anything when you start doing it 👍

**Comment by vanessa** [comment]
@aniav Thanks a lot! Can you assign the issue to me?

Another question I have, I didn't understand this part:
> (...) anonymize them in python code while processing the list (...)

What does anonymization mean in this case?

**Comment by aniav** [comment]
So right now when you go to the screen with applications and you try to order it by the score it will order it by the overall score, even the applications you didn't score yourself yet. Meaning you will see the applications in order with scores: 4.5, (hidden), (hidden), 3.5. So you already know other people have scored the people with hidden score as high.

Ideally when ordering by score we should make the hidden scores appear at the very end no matter what's their real overall score, so you don't see them between visible scores before you score yourself.

You can see an example of "wrong" ordering in the following screen:

![scores_list](https://user-images.githubusercontent.com/182546/61715910-64222080-ad5e-11e9-9c2a-67ac37424039.jpg)

**Comment by vanessa** [comment]
Got it. Thanks for clarifying.

**Comment by vanessa** [comment]
Hey @amakarudze, sorry about the delay.

I'll finally be able to tackle this issue. Is it still a priority?

**Comment by amakarudze** [comment]
Hey @vanessa. Yes, it's still important thank you.
