### ISSUE TITLE
[Copy Event] latest website should be "city" and not "city+number"

### ISSUE THREAD

**Issue by patjouk** [DjangoGirls/djangogirls#387]
When you copy an event, the latest event should `djangogirls/city` and the previous one `djangogirls/city1`.

Right now, when you do a copy event, the previous event is not changed to `city1` but stays `city` and the new one is `city1`. If you copy it to create a third event in the same city, the website will be `city12`.

**Comment by patjouk** [comment]
Update: Event website titles are not changed too.

**Comment by aniav** [comment]
This will be resolved in my PR #391. I think it's mostly done, I need to check if all places are changed.
