### ISSUE TITLE
Admin considers current events "past" and won't allow editing

### ISSUE THREAD

**Issue by davidism** [DjangoGirls/djangogirls#398]
This bit me when I wanted to update our page the morning of the event. The admin still showed all the pages, but wouldn't allow editing them; the fields were displayed as static text instead of inputs. Luckily I got around this because the admin still allowed creating completely new pages and changing their order, I just had to get it all right in one shot.

The admin should allow editing until at least the day *after* the day of the event.

**Comment by patjouk** [comment]
Will be happy to see a PR about that :+1:
