### ISSUE TITLE
chromebook starting webserver

### ISSUE THREAD

**Issue by yakonoops** [DjangoGirls/djangogirls#428]
This command:
python manage.py runserver 0.0.0.0:8000

Did not work on chromebook, user had to use port 8080 instead and add to ALLOWED_HOSTS in setup.py: django-girls-<user-name>.c9users.io

**Comment by ulgens** [comment]
Hey @yakonoops , can you please give more detail about how didn't this comand work? Is there any error message?

**Comment by aniav** [comment]
I am afraid this issue is related to the tutorial repo and doesn't belong here. We also didn't receive any clarification as what happened so I am closing for now. Feel free to open on the tutorial repo whenever you have some details. It might have already been resolved there! 🎀
