### ISSUE TITLE
Admin: Website contents not responsive on tablet

### ISSUE THREAD

**Issue by rsip22** [DjangoGirls/djangogirls#434]
I'm trying to edit the website contents (values) on the website, but I can't save the modifications because the text box overlaps the save button. Since I'm using a tablet, I can't just drag the corner to change the size of the text box. I believe a simple change on the template would fix this.

I'm attaching a screenshot of how it's displayed. Let me know if you need any more info.

![img_1933](https://user-images.githubusercontent.com/16676222/27251137-e5edf14c-5316-11e7-8827-8a4ad09e330c.PNG)

**Comment by aniav** [comment]
Go on and make it! :)

(And sorry for the late reply :))
