### ISSUE TITLE
Names of uploaded files should be unique

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#44]
Currently when someone uploads a file to Django Girls website in admin (as coach photo or sponsor logo), we don't change the name of the file, so it's easy to override someone elses file. We should change that.

**Comment by tricoder42** [comment]
Note: It shouldn't happen by default, because Django appends random hash to conflict filename (https://docs.djangoproject.com/en/1.8/ref/files/storage/#django.core.files.storage.Storage.get_available_name), but it really happened to one organizer.

**Comment by olasitarska** [comment]
Good point, if someone wants to investigate that, go ahead. Otherwise I'll try next week ;)

**Comment by tricoder42** [comment]
DjangoGirls uses S3 Storage which has a settings: `AWS_S3_FILE_OVERWRITE` https://github.com/jschneier/django-storages/blob/master/storages/backends/s3boto.py#L216

It is true by default. It should help to turn it off, but I need to test it.
