### ISSUE TITLE
Mention PyCharm as supported editor?

### ISSUE THREAD

**Issue by rix0rrr** [DjangoGirls/djangogirls#442]
Hi all,

After just coaching at a DjangoGirls event, and encouraging my own team to use PyCharm (as opposed to other editors like Atom), it strikes me how much easier my team had it than other other participants, especially around virtualenvs and running the code.

Some examples:
- It's available on all platforms, and works the same on all platforms.
- They don't have to use the console window on Windows: PyCharm has a built-in terminal that looks and works a lot better.
- They don't have to remember to manually activate the virtualenv: recent PyCharms automatically detect and activate the virtualenv.
- Running Python scripts gave less trouble: no need to remember to hit save, no need to switch back to the terminal and hit up-enter; they can just right-click in the file and select 'Run' from the menu.
- Syntax highlighting in the built-in Python REPL: makes commands easier to understand/recognize.
- Automatic syntax and semantics checking inside the editor: forgetting to put quotes around a string literal immediately underlines the offending text, with a tooltip that indicates what's wrong. This is particularly useful for new programmers who haven't completely internalized what a string literal is.

PyCharm is a great editor for Python code, with lots of conveniences. Wouldn't it be great to mention this as an option in the tutorial? 

I'd be willing to do the changes myself, if you're open to it.

**Comment by aniav** [comment]
Our main goal is to give people the option to use after the workshops. PyCharm is not cheap and if they learn using it on the workshops they will end up with trial edition expired and with no good knowledge of ther editors to use, as they don't give the mentioned power ups. I am not really a fan of mentioning it or suggesting to attendees. I would rather see a list of extensions for other editors that would give them th same conveniences.

**Comment by rix0rrr** [comment]
PyCharm's Community Edition is totally and perpetually free, so price needn't be a blocker.

**Comment by agagata** [comment]
I agree that PyCharm is a useful tool and could be used on Django Girls workshops. Having said that, I'm not sure we should teach attendees to do everything in PyCharm - knowing your way around "bare" terminal is a good skill to have.

**Comment by aniav** [comment]
Ok so with the Community Edition this is a completely different case. I didn't know about that. I am also not a fan of introducing helpers for everything we use but I accept the scope of this issue :)

**Comment by aniav** [comment]
Ah, one thing - this issue is for the tutorial repository, not the djangogirls website repository.

**Comment by rix0rrr** [comment]
Knowing your way around a terminal is definitely a good skill to have. There's a time and place to learn it though, and I'm not sure the very first day when you're going to do something you've never done before is the time to do it.

I would like to remove as much friction as possible, so the participants can get a successful result (and maybe to a little more interesting parts like HTML) quicker. They can always go back and learn the details later, when and if we've succeeded in piquing their interest.

Sorry about the misfile, btw. I mean the tutorial.

**Comment by thibaudcolas** [comment]
@rix0rrr I think you should actually close this issue and open one on the [tutorial repository](https://github.com/DjangoGirls/tutorial), so people watching that can chime in. There are already a few issues mentioning PyCharm on there.

Personally, I agree with what the tutorial says at the moment (https://tutorial.djangogirls.org/en/code_editor/):

> Most Python programmers use complex but extremely powerful IDEs (Integrated Development Environments), such as PyCharm. As a beginner, however, that's probably less suitable; our recommendations are equally powerful, but a lot simpler.

**Comment by rix0rrr** [comment]
I will move the topic.

But for someone who's barely literate in computers to learn the command line, working directories, PATH settings, and a separate editor... not sure I agree that it's simpler.

**Comment by rix0rrr** [comment]
Moved to [here](https://github.com/DjangoGirls/tutorial/issues/1169).
