### ISSUE TITLE
description block with HTML tags break the site's rendering

### ISSUE THREAD

**Issue by thibaudcolas** [DjangoGirls/djangogirls#445]
On some pages, the `description` block contains HTML tags. This is problematic because it is used inside of `<meta name="description" content="">`, which expects its value to be a string. Here is an example of the resulting invalid HTML:

```html
<meta name="description" content="<p>We just sent reset instructions to your email. If you have any issues, <a href=/account/password_reset/>try again</a> and if you still don't get anything, <a href="/contact/">say hello</a>!</p>">
```

I spotted this issue in `password_reset_done` and `password_reset_complete`: https://github.com/DjangoGirls/djangogirls/blob/0730e5a5ddffea1ab830074aaf2968c5a4f091d7/templates/registration/password_reset_done.html#L5-L7

Screenshots:

<img width="610" alt="djangogirls_password_reset_done" src="https://user-images.githubusercontent.com/877585/32218676-5fec0154-be34-11e7-8753-f8bac6e91aec.png">
<img width="698" alt="djangogirls_password_reset_complete" src="https://user-images.githubusercontent.com/877585/32218654-50c057c0-be34-11e7-86da-c900d4293dd6.png">

------------

Trying to identify why this is happening, this seems to be specific to the `registration` templates. They are (incorrectly?) reusing the `description` block as a way to generate the main content of the page:

https://github.com/DjangoGirls/djangogirls/blob/a4c9c5489dc74dbe2d9ceeaf9ee06857bc40b7b4/templates/registration/base.html#L7-L9

If that's indeed the problem, then the solution is to introduce a new block on all of those templates instead of recycling `description`. It would also be worth looking around to make sure those are the only templates that have this issue.

I'm happy to submit a PR if that's helpful.

**Comment by lightstrike** [comment]
@thibaudcolas Good catch, the registration `description` block and meta `description` block are not related in anyway, just a fun namespace collision 😅. I'd recommend changing the block name from `description` to `registration_message` or something better in [templates/registration/base.html](https://github.com/DjangoGirls/djangogirls/blob/a4c9c5489dc74dbe2d9ceeaf9ee06857bc40b7b4/templates/registration/base.html#L7-L9) and then update the reference in all templates in [templates/registration](https://github.com/DjangoGirls/djangogirls/tree/0730e5a5ddffea1ab830074aaf2968c5a4f091d7/templates/registration).

**Comment by thibaudcolas** [comment]
Thanks @lightstrike, I'll try to make a PR along those lines 🙂.
