### ISSUE TITLE
Number of past events

### ISSUE THREAD

**Issue by honzajavorek** [DjangoGirls/djangogirls#449]
Hi, I'd like to be able to get data about past events we organized in the Czech Republic, programatically (so it works without maintenance even for future). Is this information somewhere available online? If nothing, at least past places & dates would be good enough for me.

**Comment by aniav** [comment]
@honzajavorek hmm, how would you like to retrieve this data? Somewhere in the admin? If you are the organizer of all events you should have the details of past events. If you are not the thing is a bit more complicated and for now not really achievable programmatically. But let's discuss it further so we know what we can do 💃

**Comment by honzajavorek** [comment]
Meanwhile I gave up on auto-updated detailed stats like this, so never mind. I imagined something like an archive of past organized events on the website, which anyone could browse/scrape programmatically. I thought the past events are stored in database, just not listed on the site.
