### ISSUE TITLE
Don't block event deployment when we can't send an e-mail to one of the organizers

### ISSUE THREAD

**Issue by aniav** [DjangoGirls/djangogirls#454]
This is a bug we currently have. Details below:

https://opbeat.com/django-girls/djangogirlsorg/errors/88/

**Comment by ramonsaraiva** [comment]
Hey @aniav could you add more context to this since `opbeat` is gone?

**Comment by aniav** [comment]
Oh, I didn't get Opbeat is going to be gone. When an application event is being deployed we will create a webpage for it, create the accounts for organizers and send the account details to them. Sometimes the organizers' e-mails are spelled wrong causing the sending mechanism to fail. The code should take this situation into account so that failed e-mail sending doesn't cause the whole deployment to fail, leaving the deployment state unclear.

Thanks for going through the issues here 👍
