### ISSUE TITLE
Organizers can see other workshops' pages that aren't live when logged in

### ISSUE THREAD

**Issue by rsip22** [DjangoGirls/djangogirls#465]
How I noticed this:
- I was logged in as Django Girls Santa Maria organizer.
- I typed "djangogirls.org/brasilia" in the browser, which is an event that I know it will happen in four months
- It returned the template page for Brasilia, with the message "Hi there! You can see this page because you're logged in admin. When you want to make it public, go to your website section in the admin and click on 'Is live'."

This probably shouldn't happen. Not "live" pages should be shown only to it's own organizer's and to Django Girls staff/admin.

**Comment by arunikayadav42** [comment]
Can i work on this issue :)
