### ISSUE TITLE
[Score setting] The maximum score is not set.

### ISSUE THREAD

**Issue by rjs1197** [DjangoGirls/djangogirls#475]
https://github.com/DjangoGirls/djangogirls/blob/09b498300bb3bf9a69292dbd36933485a8184a2c/applications/models.py#L245

Hi. I'm djangogirls organizer in seoul, korea. I'm giving the score of the participants, but I think this function doesn't seem to work properly.

**Comment by ramonsaraiva** [comment]
Hey! I'm not able to reproduce this, could you provide a step by step flow to reproduce this issue? Keep in mind that scores are unique for an user and an application.

**Comment by rjs1197** [comment]
It's too cumbersome to implement the steps because the answer is late. If this issue is only me, We'll leave the problem next time. Thank you!

And I apologize for the short question. sorry!
