### ISSUE TITLE
Annual report is 4 years old

### ISSUE THREAD

**Issue by jasoncartwright** [DjangoGirls/djangogirls#502]
<img width="572" alt="screenshot 2019-03-08 at 11 37 30" src="https://user-images.githubusercontent.com/763913/54026665-93ad0380-4196-11e9-87d5-9f7108afccaa.png">

https://djangogirls.org/donate/

**Comment by aniav** [comment]
It's still a bit old, because it's 2016-2017, but currently there is no newer report, so I'm closing this for now 🙌
