### ISSUE TITLE
One-time donation widget isn't working

### ISSUE THREAD

**Issue by jasoncartwright** [DjangoGirls/djangogirls#503]
<img width="1137" alt="screenshot 2019-03-08 at 11 37 59" src="https://user-images.githubusercontent.com/763913/54026695-aa535a80-4196-11e9-8a6f-5336ae6b7517.png">

https://djangogirls.org/donate/

> This donation form is temporarily inactive due to a billing issue. Please contact the organization so they can rectify this. Sorry for this inconvenience.

**Comment by jasoncartwright** [comment]
Any update on this? It's been down for over 6 months now :(

**Comment by amakarudze** [comment]
@GirlGeekUpNorth do we still have this problem? I tried accessing the form now and I can fill in my details. So not sure if the billing issues were fixed so we can close this issue. Thanks.
