### ISSUE TITLE
Use webpack instead of gulp

### ISSUE THREAD

**Issue by vanessa** [DjangoGirls/djangogirls#510]

**Comment by amakarudze** [comment]
@carltongibson do we still need this or we can close it?

**Comment by vanessa** [comment]
Sorry I didn't add a proper context to the issue. When I opened a PR back in 2019, I think it was a wish that we switched to webpack some day, see https://github.com/DjangoGirls/djangogirls/pull/509#issuecomment-514207348

I can give it a try whenever possible if it's okay with you folks 🙂

**Comment by carltongibson** [comment]
Hey @vanessa — thanks for the input. 

At the moment I'm not sure of the benefit of making a change here. Gulp is updated to the latest version, and is functioning, and is relatively simple. We're not gulp experts true, but we're not web pack experts either — so I'm not at all sure what the benefit of web pack, for us, now, really is…? 🤔

The comment on #509 suggested having one window to run both processes (runserver and watch) — TBH I'd rather keep it simple. 

Happy for you to convince us that web pack is really a win, but short of that, I'd say we're better of focusing our efforts elsewhere. e.g. Updating our Python dependencies to the latest: I'd be more open to tweaking the JS/CSS tooling once those more pressing issues are resolved. 

Make sense? What do you think?
