### ISSUE TITLE
Retaining women in open source: Organising Open Source Day monthly

### ISSUE THREAD

**Issue by tapaswenipathak** [DjangoGirls/djangogirls#512]
Hi folks: Finding an active open source contributor or maintainer woman is hard. Internships give a break in open source, if observed there is no retention of women in open source and research[1] suggests. Implementing open source day per month letting woman work with mentor and contribute in an open source project they would like would be practical implementation than just publishing research and articles. Lemme know if you would interested in supporting and I will share further things.  

[1] https://en.wikipedia.org/wiki/Diversity_in_open-source_software

**Comment by das-g** [comment]
Hi Tapasweni

Thanks for reaching out to Django Girls with this project. However, be aware that https://github.com/DjangoGirls/djangogirls/issues is the issue tracker for the Django Girls _website_ https://djangogirls.org/ and the software used to run and maintain it (i.e., the source code hosted at https://github.com/DjangoGirls/djangogirls). This issue tracker is for reporting bugs and problems with the website (both technical and content-wise) and for suggesting changes and improvements of the website.

You'll probably want to contact the [Django Girls foundation](https://djangogirls.org/foundation/) about this. If you'd like to discuss the topic with the wider Django Girls community, https://djangogirls.slack.com would probably be a good place for that. The people of the foundation can probably invite you to that Slack workspace, if you aren't already in it.

@ Django Girls foundation / @ Django Girls HQ: If I'm mistaken and the Django Girls website repo issue tracker is in fact the (or a) right place to discuss topics like this, please correct me.

**Comment by tapaswenipathak** [comment]
On Sun, Aug 25, 2019 at 2:35 PM Raphael Das Gupta
<notifications@github.com> wrote:
>
> Hi Tapasweni
>
> Thanks for reaching out to Django Girls with this project. However, be aware that https://github.com/DjangoGirls/djangogirls/issues is the issue tracker for the Django Girls website https://djangogirls.org/ and the software used to run and maintain it (i.e., the source code hosted at https://github.com/DjangoGirls/djangogirls). This issue tracker is for reporting bugs and problems with the website (both technical and content-wise) and for suggesting changes and improvements of the website.
>
> You'll probably want to contact the Django Girls foundation about this. If you'd like to discuss the topic with the wider Django Girls community, https://djangogirls.slack.com would probably be a good place for that. The people of the foundation can probably invite you to that Slack workspace, if you aren't already in it.
>
> @ Django Girls foundation / @ Django Girls HQ: If I'm mistaken and the Django Girls website repo issue tracker is in fact the (or a) right place to discuss topics like this, please correct me.

Hey, these tickets are embark of the start of opensourceday; basically
mostly a poke. After an ack I am writing official proposal out. I
would love inputs on these tickets as well. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by das-g** [comment]
> Edit: There should be no space when you are tagging GitHub username.

Neither "Django Girls foundation" nor "Django Girls HQ" are GitHub usernames nor do I think there are GitHub usernames for these organizations. The "@" was merely to indicate that I'm addressing them with that paragraph and not you (@tapaswenipathak) as the issue author.

Though maybe @DjangoGirls/committers and/or @DjangoGirls/support want to comment on this?

**Comment by tapaswenipathak** [comment]
On Sun, Aug 25, 2019 at 2:51 PM Raphael Das Gupta
<notifications@github.com> wrote:
>
> Edit: There should be no space when you are tagging GitHub username.
>
> Neither "Django Girls foundation" nor "Django Girls HQ" are GitHub usernames nor do I think there are GitHub usernames for these organizations. The "@" was merely to indicate that I'm addressing them with that paragraph and not you (@tapaswenipathak) as the issue author.

Ah my bad, little thing I pointed out, sorry if you felt bad. :)
>
> Though maybe @DjangoGirls/committers and/or @DjangoGirls/support want to comment on this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni
