### ISSUE TITLE
Vaga DataAnalyst QuintoAndar

### ISSUE THREAD

**Issue by Filipe-squadlavi** [DjangoGirls/djangogirls#536]
[Oportunidades] [São Paulo/SP] [Data Analytics] [CLT]
QuintoAndar é um aplicativo para locadores e locatários cansados da burocracia do tradicional processo de locação. Consideramos cada profissional importante e responsável pelo crescimento da empresa. Não nos importamos se você usa terno e gravata, shorts com chinelos ou se você tem tatuagens e piercings. Nossa preocupação se concentra na sua qualificação profissional. Nossa equipe trabalha com tecnologia de ponta e práticas de design, para inventar ferramentas web e móveis que sejam as primeiras de seu tipo em todo o mundo.
Vale lembrar que somos uma empresa que valoriza a diversidade e inclusão. Todos os nossos cargos são abertos a pessoas com deficiência!
O desafio é para Data Analytics, pleno ou sênior, e seu trabalho é nos ajudar a medir tudo ao longo de nosso pipeline operacional, analisar dados para melhorar a tomada de decisões e ser um líder para alavancar analistas de dados. Precisamos que você saiba utilizar ferramentas/técnicas de análise de dados relevantes, como SQL, clustering, previsão, rastreamento, python, etc., assim como ferramentas de visualização, como tableau e looker, por exemplo. Gostaremos ainda mais se você possuir formação em Administração, Estatística, Engenharia ou Matemática, e ter experiência de trabalho em startups de rápido crescimento.
Ah!! Se você não é de São Paulo ou Campinas, estamos dispostos a auxiliar no seu deslocamento! Somos uma empresa de língua portuguesa mas valorizamos a diversidade e por isso recebemos candidatos estrangeiros. Se você é brasileiro, precisa ser fluente em inglês para aprender o máximo com o resto do mundo.
Contratação CLT.
Um sorriso de orelha a orelha!
Ficou interessado? Então vem fazer parte dessa equipe: https://bit.ly/3ijqgSO

**Comment by magul** [comment]
@Filipe-squadlavi we do not treat our issue tracker as a job board.

To understand the purpose of having issues here you can start here: https://guides.github.com/features/issues/
