### ISSUE TITLE
Django Girls website internationalization and localization

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#571]
Django Girls website is only displayed in English which is a problem for non-native English speakers. We would like the Django Girls website to be translated to the official language of the location of the visitor to the website, that is, should be in Portuguese for someone in a  Portuguese-speaking country or French if opened by someone in a French-speaking country.

**Comment by marksweb** [comment]
@amakarudze Assign this one to me. I'll update all the strings to use translation.

Do you have any thoughts on who can do the actual translations?

At work we use this service; https://weblate.org/en-gb/

We self host it, but it's a django based piece of software & therefore I'm not sure if they'd be open to sponsorship or some kind of deal on their hosted service.

**Comment by amakarudze** [comment]
Thanks for the suggestion @marksweb, we hadn't thought about who would do the actual translations. I thought Google Translate did that automatically but I guess we can consider applying for sponsorship from them. This is an area I think most of the trustees and support team members do not understand very well but we are willing to learn.

**Comment by vanessa** [comment]
Hey, just giving my 2 cents. In case the team is looking for localization platforms, I've used POEditor (https://poeditor.com/) before with Django and it works really well if the workflow is automatized - they also have a free unlimited plan for open source projects.
