### ISSUE TITLE
Add Stripe Integration to enable once off donations from our website

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#572]
Some corporate sponsors do not have PayPal and do not want to do bank transfers, preferring to pay by credit card. Since we removed Donorbox from the website, our supporters who want to make once-off donations via credit card face challenges donating to us. We need to add Stripe integration to our website to enable once-off donations via credit card.

**Comment by marksweb** [comment]
@carltongibson @amakarudze is this something I could take a look at? Any preferences on implementation?

**Comment by amakarudze** [comment]
Hi @marksweb. Sure, thank you. Assigning you. @carltongibson is working on something similar on another project so I am happy to let him share his insights on implementation.

**Comment by carltongibson** [comment]
Hey @marksweb -- yep, love to have you! 😀

I think the best thing to do is to use Stripe's hosted checkout to keep the implementation to a minimum. 

We'll need to coordinate on integration because there's a bit of set up on the Stripe side, but since you're volunteering I assume you're familiar with the basics here?

**Comment by marksweb** [comment]
@carltongibson yeah I'm familiar with things. I work for a company a bit like event bright, if you're familiar with them? I've built (django) sites for some large sporting events & dealt with payment gateways & fundraising platforms.

**Comment by carltongibson** [comment]
Super 👍 then let me know what you need. 😀

Thanks!

**Comment by marksweb** [comment]
@amakarudze @carltongibson 

Ok I've found a couple of hours for this.

There's effectively 3 views. The donation form, a success/confirmation page and an error page if the form doesn't validate.

![Screenshot 2021-08-11 at 01 45 59](https://user-images.githubusercontent.com/1461191/128953138-0f6f0a38-cc12-4475-b96a-d58a7cc681d1.png)

![Screenshot 2021-08-11 at 01 46 59](https://user-images.githubusercontent.com/1461191/128953143-fe568f76-a1e6-4e77-bfc4-1a411fc84af8.png)

![Screenshot 2021-08-11 at 01 47 30](https://user-images.githubusercontent.com/1461191/128953142-560b8c76-c6b7-40ce-9efd-a67915a98c70.png)

Key functionality is basically done. It's going to need some content/copy & some styling work now.

I've also added [python-dotenv](https://pypi.org/project/python-dotenv/) which is a package that injects environment variables from a `.environment` file when running `manage.py` - essentially it makes handling environment variables really easy for local development.

Commit details here if you're curious; https://github.com/marksweb/djangogirls/commits/feature/572/stripe

**Comment by marksweb** [comment]
Yeah I thought I'd start a draft PR once it's integrated to the correct place. It's a lone wolf at the moment @carltongibson 😂

**Comment by amakarudze** [comment]
Yes @marksweb, in the empty space below the heading `One time donations`. Thanks for your work in this.

> Hey @marksweb — this looks good. Do you want to open a PR?
> 
> > Key functionality is basically done. It's going to need some content/copy & some styling work now. Does it want fitting into here? https://djangogirls.org/donate/
> 
> @amakarudze ? 😀

**Comment by amakarudze** [comment]
Had to revert the changes so reopening this.
