### ISSUE TITLE
`ValueError: day is out of range for month` error causing 404 error on website when trying to apply to organize event

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#590]
Organizers get a Server error when trying to apply to organize an event due this line in core/views.py https://github.com/DjangoGirls/djangogirls/blob/main/core/views.py#L66 and results in this traceback below:

The history of this code is here: 
https://github.com/DjangoGirls/djangogirls/commit/5986ef917719356915b8b9d63b5e6faca950ef0e#diff-df4b89f5f945910d50f8ffe6681085a9ff106bf2d73be7816c10bf6b9a29ee43

```
Traceback (most recent call last):
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/djangogirls2/djangogirls.com/core/views.py", line 66, in event
    {'city': city, 'past': date(event.date.year, event.date.month, event.date.day) < now_approx}
ValueError: day is out of range for month
```

The code was introduced in this commit https://github.com/DjangoGirls/djangogirls/commit/5986ef917719356915b8b9d63b5e6faca950ef0e#diff-df4b89f5f945910d50f8ffe6681085a9ff106bf2d73be7816c10bf6b9a29ee43 trying to fix an error that was also causing server errors while trying to compare approximate dates.

**Comment by carltongibson** [comment]
Hey @amakarudze — I can't resolve this instantly: need to see what `event.date` exactly looks like — and **why** is was `str` and not an `ApproximateDate` in the original fix for #578 🤔. 

Looking at it, the `ApproximateDate` object [has `__eq__` and `__lt__` logic for the comparison](https://github.com/dracos/django-date-extensions/blob/58ac24244c9391fc5c4575cb2fa4f79a69608bf1/django_date_extensions/fields.py#L65-L89) so I'm wondering why/when that stopped working? (Same question about #578 again)

Since this is live, immediately it may be worth just **setting `past` to `False` in the context**, to allow the page to render. In that case we loose the _"This event is passed"_ logic, but at least we're not crashing, and we can resolve this properly.

**Comment by carltongibson** [comment]
(Assigning myself so it's on my list…)

**Comment by amakarudze** [comment]
Hey @carltongibson I think the server error has been an issue for more than a year now but with ApproximateDate, it would sometimes render and sometimes not resulting in multiple submissions. Not sure why that stopped working.

Ok, setting past to False in the context for now. Thanks for the advice.

**Comment by carltongibson** [comment]
OK, let's keep this open and I'll have a look. Thanks @amakarudze!

**Comment by amakarudze** [comment]
You're welcome @carltongibson. 

I have changed to False and the server error hasn't gone away. 

Also, our virtualenv is running Python 3.4 when it seems the system image is Python 3.5 as seen in the traceback above. I am also attaching the screenshot showing that. Could the Python have any effect maybe? I am running out of ideas.

<img width="755" alt="Screenshot 2021-06-30 at 19 29 17" src="https://user-images.githubusercontent.com/13593285/124006010-08488380-d9da-11eb-923a-5dd09e898c0f.png">

**Comment by carltongibson** [comment]
> I have changed to False and the server error hasn't gone away.

So... there's not enough info here for me to see what's going on. 
That's OK, let's break it down. 😀 

> I have changed to False and the server error hasn't gone away.

* Where are we seeing the errors? I think I need access to the server at this point. (Let's chat in private re that.) 
* It can't be the **same** error no? ...

            {'city': city, 'past': date(event.date.year, event.date.month, event.date.day) < now_approx}

   If that's just ` 'past': False ` now, there must be a different error. What is that? 

* I think I need to see the values stored in the DB. What is `event` actually here? (The original `str` error should not have come up if this an `ApproximateDate`... 🤔)

First step is minimum to stop the crash, then we can work on updating the Python and Django, and then the rest.

**Comment by amakarudze** [comment]
Hey @carltongibson, so the `'past': False` did solve the issue, however, there is another error for which I will create an issue as it's recurring. I will work with @GirlGeekUpNorth to get you access to the server for easier troubleshooting.

**Comment by carltongibson** [comment]
2505dd6cea1a1662166a3bf9836a7352f26b11a7 skipped the failing test here. 

Un-skip and ensure passing when fixing.
