### ISSUE TITLE
'core.models.MultipleObjectsReturned: get() returned more than one Event -- it returned 2!' is causing server error on website

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#593]
When an organizer tries to apply to organise an event, they get a server error. The traceback shows there are multiple events with the same slug as shown below:

```
Internal Server Error: /medellin/
Traceback (most recent call last):
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/djangogirls2/djangogirls.com/core/views.py", line 52, in event
    event = get_object_or_404(Event, page_url=city.lower())
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/shortcuts.py", line 87, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/home/djangogirls2/.virtualenvs/djangogirls.com/lib/python3.5/site-packages/django/db/models/query.py", line 407, in get
    (self.model._meta.object_name, num)
core.models.MultipleObjectsReturned: get() returned more than one Event -- it returned 2!
```

**Comment by marksweb** [comment]
@amakarudze I can see you've assigned this, but would you like contributions? I could take a look at ensuring unique slugs are chosen for new objects & potentially a data migration to fix existing duplicates.

**Comment by amakarudze** [comment]
Yes @marksweb. Let me unassign myself. We have been short of contributors lately but we are really looking for more contributors. Thank you. Assigning you now and removing myself and Carlton. Thanks again.

**Comment by marksweb** [comment]
Thanks @amakarudze

Happy to help out where I can 👍

**Comment by carltongibson** [comment]
Super thanks @marksweb! 

I didn't have the bandwidth to dig in yet but, it used to be that the uniqueness was enforced, adding a `-2` say. Reviewing why/when that was removed would probably pay dividends...

Reach out if you want input!

**Comment by marksweb** [comment]
Ok, so the events are powered by the `city` fields on the URL;

```
url(r'^(?P<city>[\w\d/]+)/$', views.event, name='event'),
```

But `city` is just a simple field...
```
city = models.CharField(max_length=200)
```

I can't see an override of the save to ensure a unique value. 

So I'd suggest adding a new field, `slug`, because having multiple events in a city seems fair, but adding things like `-2` to a city isn't really valid for that data.

Then the URL can be powered by the slug and I think that makes more sense.

This would likely require 3 migrations, first to add the `slug` field, second is a data migration to set that value from the current `city` field and ensure it's unique. Finally a migration to ensure `slug` is a required field.

How does that sound? @carltongibson @amakarudze

**Comment by carltongibson** [comment]
@marksweb Sounds plausible, yes. 

One thought I’d had was to somehow add a date component to the URL to make it unique. At the first application stage, there wouldn’t be a date, so `proposed` maybe, but once settled there would only ever be one event in Barcelona in May 2022, say. Not sure about whether that’s a good approach—it was just at the ideas phase—but what do you think, as an alternative to adding an additional DB field?

**Comment by marksweb** [comment]
@carltongibson yeah that sounds wise to just use the data that already exists. Although without also adding a unique together between city & date, you still can't guarantee a single object so would need to rely on form validation here.

Could potentially do something with 2 URL paths, one with year/month another with year/month/day and where 2 events exist in a city in 1 month, they then use the day also. For the most part you'd only see the first, but just in case, you'd be able to cope with extra events.

I've almost got the project running. So I'll run through things & try to avoid database changes.

Just having some grief with `gulp-stylus`. Seems to need something extra installing...

```
% gulp watch
/Users/mwalker/Sites/djangogirls/node_modules/accord/lib/adapter_base.js:105
        throw new Error("'tried to require: " + this.supportedEngines + "'.\nNone found. Make sure one has been installed!");
        ^

Error: 'tried to require: stylus'.
None found. Make sure one has been installed!
```
