### ISSUE TITLE
Email notifications not being sent to hello@djangogirls.org when organizer submits new event application

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#594]
The server error on the website is occurring just after the organizer is sent an email confirmation for a new event application but just before Django Girls is sent an email notification to hello@djangogirls.org email address. This means that there is no way for DGF to know if there are new event applications that need approval.

**Comment by carltongibson** [comment]
I can't see an error for this. Do you have a traceback?

**Comment by amakarudze** [comment]
No, none. Just realised it is being affected by the other server errors so nothing we can do here. The crash is coming from elsewhere and just affecting this email notification is sent.
