### ISSUE TITLE
Job board for global partners

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#623]
We used to have a job board for global partners but it was removed. As our mailing lists and Slack channels are no longer that active, we have limitations on how wide we can spread the news within our community when a global partner requests us to promote their job openings. It would be useful to have this as part of the website, as a standalone app with `Job` and `Global Partner` models, and we can just add jobs or turn them off through the admin.

This will help in also increasing corporate sponsorship.

**Comment by ramonsaraiva** [comment]
Done in https://github.com/DjangoGirls/djangogirls/pull/822

**Comment by ramonsaraiva** [comment]
@amakarudze I don't think I can unpin this issue, would you mind unpinning it? I believe it was resolved by #822
