### ISSUE TITLE
Document how people get added when being accepted as new organizers 

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#626]
There is a need to document how people are being added as new organizers to Django Girls website, Slack, etc. so that troubleshooting is easier when there are problems with adding new organizers.

**Comment by marksweb** [comment]
@mridubhatnagar this might be a good first issue, helping you get used to how some of the system works.

**Comment by mridubhatnagar** [comment]
@marksweb thanks, I don't know the process yet. Once I know I'll add that and raise PR for this issue.

**Comment by amakarudze** [comment]
This was resolved by this PR in our [internal wiki](https://github.com/DjangoGirls/wiki/pull/78).
