### ISSUE TITLE
`curl: (6) Could not resolve host: intake.opbeat.com` error when deploying website

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#630]
We used `opbeat` sometime back but must have been removed. However, when we do the deployment of the website after merging changes, we still get the error:

```curl: (6) Could not resolve host: intake.opbeat.com```

Need to find where in the website we are still referencing to `opbeat` and remove it.

**Comment by marksweb** [comment]
I think this would need a stacktrace because the only instance of `opbeat` in the project is in the pytest config where an environment variable is set `OPBEAT_DISABLE_SEND=true`

I also can't find `intake` in the project.

**Comment by vanessa** [comment]
Do we have a custom script that runs during deployment and doesn't live in the repo? IIRC DjangoGirls uses PythonAnywhere to host the website to maybe there's something still there?

**Comment by carltongibson** [comment]
Good spot @vanessa! 🕵️‍♀️

**Comment by amakarudze** [comment]
> Do we have a custom script that runs during deployment and doesn't live in the repo? IIRC DjangoGirls uses PythonAnywhere to host the website to maybe there's something still there?
> 
> Edit: Looks like the issue is here -> https://github.com/DjangoGirls/wiki/blob/main/howto/deploy-website.md#git-hooks

Yes, @vanessa, we do have a custom script `deploy.sh` that we run during deployment and doesn't live the repo. Thanks for spotting that! However, we no longer have the `githooks` folder in the website folder here in the repo or on PythonAnywhere. I am not sure how the `post-merge` script is now being activated and how to stop it given that the `githooks` folder doesn't exist anymore.

**Comment by amakarudze** [comment]
Thanks @vanessa. Marking this as resolved!
