### ISSUE TITLE
Sentry error reporting not working after adding new DSN

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#633]
We added the new DSN for `sentry` but errors are not appearing in on [sentry.io](sentry.io) dashboard.

**Comment by carltongibson** [comment]
It doesn't look like the init code is in settings... 

https://docs.sentry.io/platforms/python/guides/django/

🤔

**Comment by amakarudze** [comment]
It's there if you scroll to line [207](https://github.com/DjangoGirls/djangogirls/blob/main/djangogirls/settings.py#L207). Maybe adding `trace_sample_rate` will fix this? Am new to `sentry` so I have no idea.

**Comment by carltongibson** [comment]
You're right it is there... 

We need to verify the the environment variable is being set. Otherwise it should work.

**Comment by amakarudze** [comment]
We also have had this warning in the server logs for ages

```/home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/sentry_sdk/_compat.py:82: Warning: We detected the use of uwsgi with disabled threads.  This will cause issues with the transport you are trying to use.  Please enable threading for uwsgi.  (Enable the "enable-threads" flag).#012  "We detected the use of uwsgi with disabled threads.  "
```

Maybe could be the source?

**Comment by amakarudze** [comment]
> You're right it is there...
> 
> We need to verify the the environment variable is being set. Otherwise it should work.

Not sure why it wouldn't be set because it is being exported the same way as all the other environment variables.

**Comment by marksweb** [comment]
> It's there if you scroll to line [207](https://github.com/DjangoGirls/djangogirls/blob/main/djangogirls/settings.py#L207). Maybe adding `trace_sample_rate` will fix this? Am new to `sentry` so I have no idea.

The `sample_rate` argument just changes the percentage of errors that actually get reported. I'm not entirely sure why you'd use this. Perhaps if an app raised so many errors that you didn't need it to report them all.

Enabling threads for uwsgi would be a good idea - but these settings depend on what hardware is running the site as to what the CPU/memory is best suited to running.

**Comment by carltongibson** [comment]
The trace sample rate is about the new Performance monitoring Sentry have. It's bit related to error reporting. I don't think it's mandatory. 

Ref the environment variable, the settings file is pretty clear: **if it's there** make the call to sentry. If those calls aren't being made, well, is it set. (You could insert a print() in there to check the block is entered.)

It does happen that the code that's actually run isn't quite the code we think it is. Wrong versions, wrong paths and so on. So it's a question of double checking each step until the point at which it's going wrong shows itself. (I appreciate that's not much actual help.)

**Comment by marksweb** [comment]
> We also have had this warning in the server logs for ages
> 
> ```
> /home/djangogirls2/.virtualenvs/djangogirls3/lib/python3.7/site-packages/sentry_sdk/_compat.py:82: 
> Warning: We detected the use of uwsgi with disabled threads.  This will cause issues with the transport 
> you are trying to use.  Please enable threading for uwsgi.  (Enable the "enable-threads" flag).#012 
>  "We detected the use of uwsgi with disabled threads.  "
> ```
> 
> Maybe could be the source?

I've done a bit of reading about what python anywhere offers and essentially they don't support running multiple threads.

They just let you pick out your wsgi app and their server config runs that.

I wonder if you can tell sentry that you're running without threads 🤔

**Comment by marksweb** [comment]
> The trace sample rate is about the new Performance monitoring Sentry have. It's not related to error reporting. I don't think it's mandatory. 

I believe there is a sample rate available to the error reporting as well as performance monitoring: https://docs.sentry.io/platforms/python/configuration/options/#sample-rate

**Comment by amakarudze** [comment]
Just realised we are running 3 apps and I had only added the SENTRY_DSN environment variable to one wsgi and not the other 2 that's why it wasn't picked up. Will check to see if I experience any deployment or server errors to see if they are logged before closing this issue.

**Comment by marksweb** [comment]
@amakarudze Now that this is resolved, I could add a version number to the project and link it to Sentry.

It'd need to be incremented as part of your release process after merging PRs to signify the kind of changes (major, minor, patch) that are due to deploy, but on the whole, it'll track sentry issues against the release to show where issues came in.

**Comment by amakarudze** [comment]
@marksweb that'd be great. Thanks!

**Comment by amakarudze** [comment]
This is now working so closing the issue!
