### ISSUE TITLE
Introduce flake8 checks for code quality

### ISSUE THREAD

**Issue by marksweb** [DjangoGirls/djangogirls#635]
I'm a fan of good quality code so keen to introduce [flake8](https://flake8.pycqa.org/en/latest/) to the project & have it running along with the actions.

There's about 150 issues that it's identifying, so wouldn't be a small PR, but it is just formatting, not functionality.

Issues should be fewer if the code quality is higher.

Would this be a welcome feature?

**Comment by carltongibson** [comment]
Hey @marksweb -- do you think setting up pre-commit would be worth it here?

**Comment by marksweb** [comment]
Yeah that'd be my preference @carltongibson
