### ISSUE TITLE
Github and Sentry integration

### ISSUE THREAD

**Issue by marksweb** [DjangoGirls/djangogirls#639]
Sentry can be integrated with github to track releases and hopefully track commits and link errors to github issues.

https://sentry.io/integrations/github/

This needs some poking around in the sentry settings, but I imagine it'll be fairly simple to setup.

Depending on how the release tracking keeps a record of the website, I can then do any additional work to set it up. But it may be able to just track releases based on git tags which can be done from here when a release is deployed.

**Comment by marksweb** [comment]
@amakarudze first job on this one is for you I think.

I've just tried it out myself & setup a new sentry account, then gone to settings -> integrations and added github.

<img width="963" alt="Screenshot 2021-08-16 at 23 26 30" src="https://user-images.githubusercontent.com/1461191/129637319-b2423d40-483a-4ebe-bc64-8e38d6f30e54.png">


If you configure that, it'll start to give a good idea as to what it does without any additional config after the next deployment.

**Comment by marksweb** [comment]
The `sentry-cli` should be possible to integrate into the build script to associate commits with releases;

https://docs.sentry.io/product/sentry-basics/guides/integrate-frontend/configure-scms/

**Comment by amakarudze** [comment]
> @amakarudze first job on this one is for you I think.
> 
> I've just tried it out myself & setup a new sentry account, then gone to settings -> integrations and added github.
> 
> <img alt="Screenshot 2021-08-16 at 23 26 30" width="963" src="https://user-images.githubusercontent.com/1461191/129637319-b2423d40-483a-4ebe-bc64-8e38d6f30e54.png">
> 
> If you configure that, it'll start to give a good idea as to what it does without any additional config after the next deployment.

@marksweb Done!

**Comment by amakarudze** [comment]
So I have 3 errors on the website being reported by Sentry. Is there any easy way to create the issues on GitHub @marksweb? I am getting started with Sentry here. Thanks for the help.

**Comment by marksweb** [comment]
<img width="327" alt="Screenshot 2021-08-18 at 12 27 34" src="https://user-images.githubusercontent.com/1461191/129890333-cbc72ccd-b8ec-4eaa-aa09-48beb01aa390.png">
You should get something in the sidebar (right side) that looks like this when looking at an issue.

I'm just looking at this myself, because I only setup my first integration between github & sentry when I posted the screenshot above. At work we use Jira and AWS, so this is a little different. I've reached out to Sentry on twitter. Potentially github issues don't integrate, but we'll have to see.

**Comment by amakarudze** [comment]
Thanks @marksweb!

**Comment by marksweb** [comment]
Ok @amakarudze I have some more info following a conversation with a sentry engineer.

The issue tracking is a feature of paid plans, however djangogirls should qualify for a sponsored plan.

For reference, here's my conversation; https://twitter.com/mark_story/status/1428070489147285509

**Comment by amakarudze** [comment]
Thanks @marksweb. Just created 3 issues from Sentry, yay!

**Comment by marksweb** [comment]
@amakarudze thats excellent news, so you've been able to get the sponsored plan sorted?

The other thing to look at on there was single sign on from github. That should provide people in the github organisation with access to sentry, or at least make it easier.

**Comment by amakarudze** [comment]
Yes, the sponsored plan was sorted more than a week ago @marksweb. I thought I gave that feedback already.

**Comment by marksweb** [comment]
There's a good chance you did & I've just forgotten 🤦‍♂️😂
