### ISSUE TITLE
Update Patreon figure on website homepage and donate page

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#660]
We have just had a new global partner joining us on Patreon bringing our figure from `$701` to `$806`, which is `54%` of our target goal. We need to update this change on these pages:
* [website homepage](https://github.com/DjangoGirls/djangogirls/blob/main/templates/core/index.html#L120-L123) `templates/core/index.html` 
* [donate page](https://github.com/DjangoGirls/djangogirls/blob/main/templates/donations/donate.html#L94-L96) `templates/donations/donate.html`.

**Comment by amakarudze** [comment]
@mridubhatnagar I think this is a beginner-level issue that you can tackle. I have even pointed to the files that need updating and supplied the details. Shall I assign this to you?

**Comment by mridubhatnagar** [comment]
Thanks @amakarudze.

Yes sure, you can assign it to me.

**Comment by amakarudze** [comment]
@mridubhatnagar please note I have updated the figures again.

**Comment by amakarudze** [comment]
@mridubhatnagar are you still working on this?

**Comment by amakarudze** [comment]
@mridubhatnagar I haven't heard from you in a while so I am taking this up now.
