### ISSUE TITLE
TinyMCE - Unable to switch to "Source Code" from the toolbar

### ISSUE THREAD

**Issue by Mahalinoro** [DjangoGirls/djangogirls#688]
![image (1)](https://user-images.githubusercontent.com/52964908/133939364-2948df45-03d4-42be-8c35-d440bf93d25e.png)
 I would like to edit the HTML code directly for our website contents (Django Girls Antananarivo workshop), but it doesn't have that option even if it says the code plugin is available.

**Comment by amakarudze** [comment]
Hey @marksweb, does `tincymce` allow editing the HTML code directly?

**Comment by marksweb** [comment]
@amakarudze I'm not sure. Would need to look at the config options.
