### ISSUE TITLE
Flake 8 integrations failing

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#710]
flake8.yml file does not mention Python version and hence it's running using Python 3.10 and failing. We are using Python 3.9 in dev and production and hence the workflow should use 3.9. The flake8.yml file needs to be updated to reflect this change.

**Comment by marksweb** [comment]
@amakarudze where have you seen this problem? Flake8 rules shouldn't change between python versions so I'm curious.

There's also some more useful things the pre-commit could be doing so happy to sort this.

**Comment by amakarudze** [comment]
It listed a failure and I jumped to conclusions without reading the error messages well, I guess I just saw the version differences and thought that was the root cause. My bad @marksweb. Just closed this.
