### ISSUE TITLE
API for pulling stories from blog to website

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#714]
Currently, our blog posts are published on Tumblr and have to be manually added to the Story model for them to appear on the website. It would be great to have an API do that for us so that we don't have outdated posts listed on the website because someone forgot to update the model after publishing a new post.

Tumblr has an [API Documentation](https://www.tumblr.com/docs/en/api/v2) that could be explored and an API developed to make this work.

**Comment by amakarudze** [comment]
Thanks @ramonsaraiva for picking this up.

**Comment by ramonsaraiva** [comment]
Created a draft pull request with one approach I had in mind for triggering this update - let me know what you guys think about it and I'll finalize the test cases and missing pieces of it.
