### ISSUE TITLE
Application open/close dates don't work

### ISSUE THREAD

**Issue by williln** [DjangoGirls/djangogirls#72]
I noticed this first when I set my application to open on July 1 at 6am, but it was open on June 30 at 10pm (PST). I wondered if it was just a time zone issue. 

Then, I needed to close my app after it was open because of an unrelated issue, so I changed the open date to July 6, but the app is currently open. 

http://djangogirls.org/djangoconus/apply/
![screen shot 2015-07-02 at 8 41 35 am](https://cloud.githubusercontent.com/assets/2286304/8481104/30d694e4-2096-11e5-8bf1-0920a17d0a8f.png)

**Comment by olasitarska** [comment]
Hah, I was confused by this for a couple of days, because we've got tests for that and stuff. Then it hit me: you can see the application form, because you're logged in as organizer. Try visiting this in incognito window and you won't be able to see the application form :)
