### ISSUE TITLE
Clean up settings.py and .environment by removing unused variables like jobs email, store discount and meetups email 

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#736]
We don't have a store open for now and no longer have jobs and meetups email accounts but they are still in settings. The variables need to be removed from `settings.py` and environment variables.

**Comment by amakarudze** [comment]
Hello @anaschwendler, do you think this is something you can tackle? I can help with variables to be removed.

**Comment by anaschwendler** [comment]
On it now! 🍀
