### ISSUE TITLE
Provide an easy way to duplicate an event if the organize need EN and non-EN event websites

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#741]
Some organizers request two event websites, one in English and another in their native language. Currently, one has to manually create the second website, needing to copy the information from the other event. There is need to provide an easier way to duplicate the events.

**Comment by marksweb** [comment]
@amakarudze I could probably implement this, along with an admin action to duplicate events possibly.

Could you let me know your thoughts on what the user flow might be for this? I can't quite remember exactly how things work other than the organise wizard that lets people apply to run a workshop.

**Comment by amakarudze** [comment]
Thanks, @marksweb. An event is usually created by clicking Deploy in the admin section on the Event Application page. Duplicating it for now we are using Create New Event on the Event List page and the copy everything manually. To duplicate an event would require adding a button Duplicate Event on the Event Page, asking the new URL for the event, and then copying everything else for that event within the admin section. Let me know if this makes sense or do I need to get screenshots.

**Comment by amakarudze** [comment]
Hey @marksweb, are you working on this?

**Comment by marksweb** [comment]
@amakarudze I've not had chance to yet.

**Comment by marksweb** [comment]
@amakarudze just looking at some code related to this type of functionality and thought the approach might help.

We've got a model which has a method to clone itself along with the objects it relates to (placeholders);

```
class Template(models.Model):

    class Meta:
        """
        Metadata
        """
        app_label = 'pdf_templates'
        verbose_name = _('Template')
        verbose_name_plural = _('Templates')

    name = models.CharField(
        verbose_name=_('name'),
        max_length=255,
        help_text=_('Name of this template, for admin purposes'),
    )

    def __str__(self):
        """
        String representation
        """
        return self.name

    @property
    def cached_placeholders(self):
        """
        Return the Placeholders used to render content into this Template,
        from the cache if possible, else from the database

        Note: the Placeholders will be returned in page/sort order, i.e. in
        order of application

        :return: the cached Placeholders attached to this Template, in
                 page/sort order, ready to render
        :rtype: list of pdf_templates.models.Placeholder
        """
        from .placeholder import Placeholder
        return Placeholder.cached_for_template(self)

    def clone(self):
        """
        Clone this Template, and all child Placeholders

        :return: the cloned Template
        :rtype: Template or NoneType
        """
        if not self.id:
            # this Template isn't saved yet...
            return None

        # first, get a copy of self (that isn't self), we'll save this into
        # the database as a new record by wiping the ID and re-saving
        clone = Template.objects.get(id=self.id)
        clone.id = None
        clone.name += ' (clone)'
        clone.slug = None
        clone.save()

        # clone child Placeholders
        for placeholder in self.cached_placeholders:
            placeholder.id = None
            placeholder.template = clone
            placeholder.save()

        return clone
```

In the template admin, the action to clone looks like this;

```
    def clone_action(self, request, queryset):
        """
        Clone the selected Templates, making a copy of:
         - the Template
         - all child Placeholders
        """
        count = 0
        for template in queryset:
            template.clone()
            count += 1

        messages.success(
            request,
            '{} template{} cloned'.format(
                count,
                '' if count == 1 else 's'
            )
        )
    clone_action.short_description = 'Clone selected Templates'
```

This is quite a neat way of doing it. Keeps the logic out of the admin. Hopefully it's useful.

**Comment by amakarudze** [comment]
Hey @marksweb, agreed, this could be a net way of doing this.

**Comment by marksweb** [comment]
I think it's the most efficient way because you don't have to specify fields and maintain the function if fields are added. It's just simple.
