### ISSUE TITLE
Make djangogirls.org HTTPS only

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#75]
Now that we have SSL for djangogirls.org, it'd be good to redirect all http requests there. It probably needs a middleware.

**Comment by aniav** [comment]
If we want the whole domain to be behind HTTPS we need to turn it on in the server settings and set redirects there, Django doesn't have to know about it at all AFAIK.

**Comment by olasitarska** [comment]
I don't think Heroku can do that

**Comment by aniav** [comment]
Oh... /o\

**Comment by olasitarska** [comment]
Exactly :D
