### ISSUE TITLE
Add robots.txt and sitemap to website

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#766]
Our blog posts are not listed by Google's SEO (search engine optimization) algorithms because our site does not have a robots.txt or sitemap. Need to add them so that global sponsors can have their posts in Google's SEO for their increased visibility. This issue is based on a question from PostHog.

**Comment by mikefrederick** [comment]
This is the robots.txt and the sitemap:

https://blog.djangogirls.org/robots.txt
https://blog.djangogirls.org/sitemap1.xml

*Here you can see Bing indexing this post:*
https://www.bing.com/search?q=flatirons+development+django+girls&form=QBLH&sp=-1&pq=flatirons+development+django+girl&sc=0-33&qs=n&sk=&cvid=F7081B3C078A4E68B30D8074D1F75E6E

*Ahrefs and Google do not. Example:*

https://www.google.com/search?q=flatirons+development+django+girls&source=hp&ei=QDRYYqHMEb_JptQP7rOt6AQ&iflsig=AHkkrS4AAAAAYlhCUMaZNRIjyPZL10ZHXrc3dm8q0Lnp&ved=0ahUKEwih7Kea5pP3AhW_pIkEHe5ZC00Q4dUDCAk&uact=5&oq=flatirons+development+django+girls&gs_lcp=Cgdnd3Mtd2l6EAMyCAgAEIAEEMkDMgUIABCABDIGCAAQFhAeMgYIABAWEB4yBggAEBYQHjIFCAAQhgMyBQgAEIYDMgUIABCGAzoRCC4QgAQQsQMQgwEQxwEQ0QM6CAgAELEDEIMBOgsIABCABBCxAxCDAToOCC4QgAQQsQMQxwEQ0QM6EQguEIAEELEDEIMBEMcBEKMCOg4ILhCABBCxAxDHARCjAjoICC4QgAQQsQM6CwguEIAEEMcBEK8BOggIABCABBCxAzoKCAAQsQMQgwEQCjoLCC4QgAQQsQMQ1AI6DgguEIAEEMcBEK8BENQCOg4ILhCABBCxAxDHARCvAToRCC4QgAQQsQMQxwEQrwEQ1AI6DgguELEDEIMBEMcBEK8BOhEILhCABBCxAxCDARDHARCvAToHCAAQgAQQCjoLCC4QgAQQxwEQ0QM6CgguEMcBEK8BEAo6BAgAEAo6BwgAELEDEA06BAguEA06CgguEMcBEK8BEA06EAguELEDEIMBEMcBEK8BEA06CgguEMcBENEDEA06DQguEMcBEK8BENQCEA1QAFifN2C9OGgGcAB4AYABiwKIAckVkgEHMTAuMTIuMpgBAKABAQ&sclient=gws-wiz

**Comment by amakarudze** [comment]
Thanks @mikefrederick, will take a look at. Google's documentation for this.
