### ISSUE TITLE
Use .nvmrc to Specify Node Version

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#768]
When the system image was upgraded, it was difficult to set up gulp because the node version of the old project had been lost. This feature will enable us to lock the version of node in the event a system image upgrade happens again on the server.

https://tecadmin.net/lock-application-with-specific-node-version/

**Comment by marksweb** [comment]
@amakarudze What version does it need?

**Comment by amakarudze** [comment]
Hey @marksweb, Node v14.17.3 and npm 6.14.13. Thanks for looking into this! 🥳✨

**Comment by ramonsaraiva** [comment]
I believe we can close this one.
