### ISSUE TITLE
Move from using archived `slacker` API to Slack's own API to integrate website and Slack

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#787]
We are still using [slacker](https://github.com/os/slacker) API to integrate the website despite the API being archived in 2020 and Slack introducing their own [API](https://api.slack.com/). Since [slacker](https://github.com/os/slacker) is no longer maintained, we need to update our website to use [Slack's own API](https://github.com/slackapi/python-slack-sdk).

**Comment by vanessa** [comment]
Do we still want this one? If yes, I can take a stab at it.

**Comment by amakarudze** [comment]
> Do we still want this one? If yes, I can take a stab at it.

Yes please @vanessa. Thank you.
