### ISSUE TITLE
Need to add "position" for sponsor, but there is no input there. 

### ISSUE THREAD

**Issue by williln** [DjangoGirls/djangogirls#79]
When I try to add a sponsor, I get an error that the "position" field is required, but there is no input there for me to change. This isn't an error I got when I added the Portland sponsors (and again there is no input for that column), but it's an error I'm getting when I try to add sponsors to the Austin event. 

Note: In the screenshot, I did have a photo added for a logo; when I tried to save the page, the logo I uploaded disappeared, so the error isn't pointing to that. 

<img width="935" alt="screen shot 2015-07-08 at 3 10 01 pm" src="https://cloud.githubusercontent.com/assets/2286304/8583592/a32acb68-2583-11e5-8e4e-6aaaf135cff5.png">

**Comment by aniav** [comment]
Fixed that in 39965fca837b4bf414b17678939e5f6ab2a96373 right now! :)
