### ISSUE TITLE
Event page throwing 500 error

### ISSUE THREAD

**Issue by vanessa** [DjangoGirls/djangogirls#820]
This event page shows a 500 error message when accessed: https://djangogirls.org/en/maceio/

Do we know what's causing this?

**Comment by ramonsaraiva** [comment]
<img width="969" alt="image" src="https://user-images.githubusercontent.com/5559120/210153435-f3c894a2-b706-4606-905f-f37cc081b02e.png">

I'm not sure how we ended up with 2 events for `/maceio/`, but it is related to the page expecting to have a single event in this `get_object_or_404` call `event_obj = get_object_or_404(Event, page_url=page_url.lower())` (https://github.com/DjangoGirls/djangogirls/blob/main/core/views.py#L59)

**Comment by ramonsaraiva** [comment]
https://github.com/DjangoGirls/djangogirls/issues/819 probably related

**Comment by vanessa** [comment]
@ramonsaraiva thanks for looking into this! I'll close this one since it's most likely a duplicate of #819 and #818 as you mentioned
