### ISSUE TITLE
CharField and TextField should generally not be nullable

### ISSUE THREAD

**Issue by uranusjr** [DjangoGirls/djangogirls#83]
Related to 9cf101954. I fixed `templates/event.html` with a `default_if_none:''` filter to avoid invalid CSS:

``` html
<style>
    None
</style>
```

but this really should have been enforced in the model, since it doesn’t really make sense to distinguish between `None` and `''` (empty string) for this attribute. The same can be said with `EventPage`’s `title`, `description`, and many other fields holding text contents.

**Comment by lilithxxx** [comment]
Assign this issue to me please as I am new to open source contributions. Please guide me how to do it.

**Comment by kurianbenoy** [comment]
Can I take up this Issue?

All I need to change is In the model I need to set  `default=' '` and remove all `null = True`

**Comment by EmadMokhtar** [comment]
@kurianbenoy If you set `blank=True` Django will save the default as empty string, so no need for `default=''`

[blank docs](https://docs.djangoproject.com/en/2.0/ref/models/fields/#django.db.models.Field.blank)

**Comment by kurianbenoy** [comment]
Thanks @Emad ,
Can I take up this issue?

**Comment by EmadMokhtar** [comment]
@kurianbenoy I think you can for sure, it's open source and you'll help the community ;).

You can check more with @olasitarska or @patjouk

**Comment by khdc-me** [comment]
Hi everyone. What's the status on this? I'd like to take a stab at it, if at all poss.

**Comment by stsewd** [comment]
Looks like this was already solved in https://github.com/DjangoGirls/djangogirls/pull/483

**Comment by PluckyPrecious** [comment]
I think this issue needs to be closed.
