### ISSUE TITLE
Validation of application scoring form

### ISSUE THREAD

**Issue by olasitarska** [DjangoGirls/djangogirls#86]
![screen shot 2015-07-14 at 9 47 18 am](https://cloud.githubusercontent.com/assets/527795/8676396/d9797c2a-2a0e-11e5-8833-570c07c09b61.png)

**Comment by williln** [comment]
@olasitarska What do you want to happen here? Have it average out to 0.5?

**Comment by olasitarska** [comment]
Sorry for not making that clear, here it is:
- In the row with empty person -- this person doesn't have first_name and last_name setup. In this case, we should display email field.
- Ola Sendecka and empty person shouldn't be allowed to add a score with score None and comment None.

**Comment by aniav** [comment]
This is also done, closing!
