### ISSUE TITLE
"Save and go to next" stopped working

### ISSUE THREAD

**Issue by williln** [DjangoGirls/djangogirls#87]
About half an hour ago, the "Save and go to next" button stopped working, and instead just redirects back to the list of applications. I refreshed my browser, in case it was some browser-based issue, but that didn't work.

**Comment by olasitarska** [comment]
It may mean that you scored all applications. Is that the case? 

If so, we should add a warning message when it happens -- you're the second person to report it :)

**Comment by williln** [comment]
@olasitarska Nope, I still have applications to score. I just have to find them manually. :-/

**Comment by olasitarska** [comment]
Ok, there is a bug then :)

**Comment by williln** [comment]
:bug: :beetle: :bee:

**Comment by williln** [comment]
So this started working again? IDK why.

**Comment by phalt** [comment]
@williln is this behaviour still present when you do finish the list? I think I implemented a bit of this so I can have a look into it.

**Comment by williln** [comment]
@phalt This isn't happening for me anymore. Granted, when it started happening, it was halfway through scoring about 50 applications. Since then, I am only scoring 2 or 3 at a time. I'm comfortable closing the issue, though, since i'm not getting it anymore.
