### ISSUE TITLE
Remove Google Groups mention and change instructions for Slack in new organizer email

### ISSUE THREAD

**Issue by amakarudze** [DjangoGirls/djangogirls#888]
When a new event is deployed, organizers are told to join organizers' Google Group which no longer exists. They are also told that a Slack invite has been sent to them when at the moment we are unable to send automatic Slack invites. The email template for new events email should reflect this change.

Templates to be edited;
- [templates/emails/new_user.html](https://github.com/DjangoGirls/djangogirls/blob/main/templates/emails/new_user.html)
- [templates/emails/existing_user.html](https://github.com/DjangoGirls/djangogirls/blob/main/templates/emails/existing_user.html)
- [templates/emails/event_deployed.html](https://github.com/DjangoGirls/djangogirls/blob/main/templates/emails/organize/event_deployed.html)

**Comment by amakarudze** [comment]
Yes, sure @anaschwendler. Please do.  Be sure to say *If you are not our Slack channel, please reach out to us and we will invite you and your team to Slack.* in place of *We have sent you a Slack invite.*.

**Comment by anaschwendler** [comment]
I'm there, all good!
I'm on a work break, so I might be working on some issues. We can also speak if you want to send me some urgent topics!

See you, and have a lovely week!

**Comment by amakarudze** [comment]
Yay! That's awesome @anaschwendler. Thanks, I will certainly reach out. See you and have a lovely week as well.

**Comment by amakarudze** [comment]
Addressed by #894
