### ISSUE TITLE
Incomplete requirements.txt

### ISSUE THREAD

**Issue by Nandika-A** [DjangoGirls/djangogirls#927]
For set up using python3.10.12, I got the following error while installing requirements:
<img width="693" alt="Screenshot 2024-01-03 180837" src="https://github.com/DjangoGirls/djangogirls/assets/93462818/7d259c1f-0b25-47d4-acfd-6d5476054ae2">
<img width="637" alt="Screenshot 2024-01-03 180850" src="https://github.com/DjangoGirls/djangogirls/assets/93462818/24a480ec-748d-44ca-b6fd-1ceb4ff6c591">
 

This can be solved using : `sudo apt install python3.11-dev libpq-dev`

After following all the steps in the contribution guide for non-docker development environment, some dependencies remain from getting installed, even after installing both requirements.txt and requirements.in. These have to be installed separately using pip, though they are already installed. 
Some of these are:
1. captcha
2. captcha.fields
3. dotenv
4. dj-database-url
5. sentry-sdk
6. django-admin-sortable2
7. django-bleach

I am getting this error when I run migrate:
<img width="379" alt="Screenshot 2024-01-03 180651" src="https://github.com/DjangoGirls/djangogirls/assets/93462818/d6c777f2-8522-4d90-b91e-b33e4c165125">

Can you suggest some way of solving this?

**Comment by amakarudze** [comment]
Let me check and get back to you, though I have never encountered this issue before. Will check if any of the requirements are missing.

**Comment by Nandika-A** [comment]
> @Nandika-A the build for `psycopg-binary` fails and hence your `pip install -r requirements.txt` fails before installing those dependencies you just listed.
> 
> What I usually do is `pip install psycopg-binary` separately which installs the latest version of `psycopg-binary`. After that, I pin the version of `psycopg-binary` for my local version to the one I just installed before running `pip install -r requirements.txt` again to install dependencies which were not installed.
> 
> Since we do not have this issue in our CI and production, I just know it's my own plaform issues so I change back to the pinned version once my local environment is up and running.
> 
> I can add these instructions to the contributing guide as troubleshooting tips but this should help you navigate the issue for now.
> 
> Hope this helps!

Got it @amakarudze! Thanks for the help
