### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Manishmkr** [DjangoGirls/djangogirls#96]
from django.template import context,engine, template doesnot exist
ImportError:cannot import name 'context'

I was in django tutorial intro to html part and this error is showing when i give
python manage.py runserver     command in console windows

**Comment by phalt** [comment]
Hey @Manishmkr, I think you're looking at the wrong GitHub repo? I think you'll want to file this under [DjangoGirls/tutorial](https://github.com/DjangoGirls/tutorial/issues)

**Comment by olasitarska** [comment]
Thanks @phalt!
